#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define NOTOSERIF_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_12_regular.h",
  "./notoserif_12_bold.h",
  "./notoserif_12_bolditalic.h",
  "./notoserif_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSERIF_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_14_regular.h",
  "./notoserif_14_bold.h",
  "./notoserif_14_bolditalic.h",
  "./notoserif_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSERIF_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_16_regular.h",
  "./notoserif_16_bold.h",
  "./notoserif_16_bolditalic.h",
  "./notoserif_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSERIF_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_18_regular.h",
  "./notoserif_18_bold.h",
  "./notoserif_18_bolditalic.h",
  "./notoserif_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_12_regular.h",
  "./notosans_12_bold.h",
  "./notosans_12_bolditalic.h",
  "./notosans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_14_regular.h",
  "./notosans_14_bold.h",
  "./notosans_14_bolditalic.h",
  "./notosans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_16_regular.h",
  "./notosans_16_bold.h",
  "./notosans_16_bolditalic.h",
  "./notosans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_18_regular.h",
  "./notosans_18_bold.h",
  "./notosans_18_bolditalic.h",
  "./notosans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

# Keep legacy IDs stable for existing built-in UI fonts. These constants are
# used as runtime/cache keys, so changing them would invalidate unrelated state.
echo "#define UI_10_FONT_ID (22918846)"
echo "#define UI_12_FONT_ID (1635686837)"
echo "#define SMALL_FONT_ID (674098198)"

echo "#define IBMPLEXMONO_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ibmplexmono_10_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define IBMPLEXMONO_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ibmplexmono_12_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

cat <<'EOF'

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IBMPLEXMONO_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IBMPLEXMONO_12_FONT_ID != 0, "Font ID collision with sentinel");
EOF
