#!/usr/bin/env python3
"""
Build a Traditional Chinese → Simplified Chinese codepoint mapping table
from the Unicode Unihan database (kSimplifiedVariant field).

Downloads Unihan_Variants.txt from unicode.org if not cached locally.
Output: data/trad_to_simp.tsv (format: TRAD_HEX<TAB>SIMP_HEX)
"""

import os
import urllib.request
import zipfile
import io

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data")

UNIHAN_VARIANTS_CACHE = os.path.join(DATA_DIR, "Unihan_Variants.txt")
UNIHAN_ZIP_URL = "https://unicode.org/Public/UCD/latest/ucd/Unihan.zip"
OUTPUT_FILE = os.path.join(DATA_DIR, "trad_to_simp.tsv")


def download_unihan_variants():
    """Download Unihan.zip and extract Unihan_Variants.txt."""
    print(f"Downloading {UNIHAN_ZIP_URL} ...")
    response = urllib.request.urlopen(UNIHAN_ZIP_URL)
    zip_data = response.read()

    with zipfile.ZipFile(io.BytesIO(zip_data)) as zf:
        with zf.open("Unihan_Variants.txt") as f:
            content = f.read()

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(UNIHAN_VARIANTS_CACHE, "wb") as f:
        f.write(content)
    print(f"  Cached to {UNIHAN_VARIANTS_CACHE}")


def load_unihan_variants():
    """Load Unihan_Variants.txt and extract kSimplifiedVariant mappings.

    Returns dict: Traditional codepoint (int) -> Simplified codepoint (int).
    For one-to-many mappings, uses the first variant.
    """
    if not os.path.exists(UNIHAN_VARIANTS_CACHE):
        download_unihan_variants()

    mapping = {}
    with open(UNIHAN_VARIANTS_CACHE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            if parts[1] != "kSimplifiedVariant":
                continue

            # parts[0] is like "U+570B", parts[2] is like "U+56FD" or "U+56FD U+570B"
            trad_cp = int(parts[0][2:], 16)
            # Take first variant for one-to-many mappings
            simp_str = parts[2].split()[0]
            simp_cp = int(simp_str[2:], 16)

            mapping[trad_cp] = simp_cp

    return mapping


def main():
    print("Loading Unihan kSimplifiedVariant mappings...")
    mapping = load_unihan_variants()
    print(f"  Found {len(mapping)} Traditional → Simplified mappings")

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Traditional → Simplified Chinese codepoint mapping\n")
        f.write("# Generated by build_trad_simp_mapping.py from Unihan_Variants.txt\n")
        f.write("# Format: TRAD_HEX<TAB>SIMP_HEX\n")
        for trad_cp in sorted(mapping.keys()):
            simp_cp = mapping[trad_cp]
            f.write(f"0x{trad_cp:04X}\t0x{simp_cp:04X}\n")

    print(f"\nOutput: {OUTPUT_FILE}")
    print(f"Total mappings: {len(mapping)}")


if __name__ == "__main__":
    main()
