#pragma once
// Generated by generate_fixtures.py from data/NotoSansBengali-Regular.layout. Do not edit.

#include <cstdint>

constexpr uint32_t kFixturePpem26_6 = 2133;

struct ExpectedGlyph {
  uint16_t gid;
  uint16_t advance12_4;
  int8_t dx;
  int8_t dy;
};

struct ExpectedShaping {
  const char* utf8;
  const ExpectedGlyph* glyphs;
  uint8_t count;
};

constexpr ExpectedGlyph kGlyphs0[] = {{22, 430, 0, 0}, {49, 390, 0, 0}, {46, 326, 0, 0}};
constexpr ExpectedGlyph kGlyphs1[] = {{57, 142, 0, 0}, {22, 430, 0, 0}};
constexpr ExpectedGlyph kGlyphs2[] = {{370, 193, 0, 0}, {32, 292, 0, 0}, {327, 142, 0, 0},
                                      {49, 390, 0, 0},  {44, 318, 0, 0}, {12, 285, 0, 0}};
constexpr ExpectedGlyph kGlyphs3[] = {{370, 193, 0, 0}, {22, 430, 0, 0}, {56, 142, 0, 0}};
constexpr ExpectedGlyph kGlyphs4[] = {{370, 193, 0, 0}, {22, 430, 0, 0}, {69, 142, 0, 0}};
constexpr ExpectedGlyph kGlyphs5[] = {{50, 363, 0, 0},   {22, 430, 0, 0}, {59, 0, -13, 0}, {203, 403, 0, 0},
                                      {275, 0, -26, -2}, {49, 390, 0, 0}, {56, 142, 0, 0}};
constexpr ExpectedGlyph kGlyphs6[] = {
    {206, 408, 0, 0}, {253, 0, -24, 1}, {22, 430, 0, 0}, {56, 142, 0, 0}, {50, 363, 0, 0}};
constexpr ExpectedGlyph kGlyphs7[] = {{57, 142, 0, 0},  {44, 318, 0, 0}, {39, 295, 0, 0},
                                      {105, 144, 0, 0}, {56, 142, 0, 0}, {52, 332, 0, 0},
                                      {56, 142, 0, 0},  {24, 345, 0, 0}, {48, 318, 0, 0}};
constexpr ExpectedGlyph kGlyphs8[] = {
    {22, 430, 0, 0}, {123, 379, 0, 0}, {61, 0, -8, 0}, {104, 0, -9, 0}, {22, 430, 0, 0}};
constexpr ExpectedGlyph kGlyphs9[] = {{52, 332, 0, 0}, {63, 193, 0, 0},  {44, 318, 0, 0}, {240, 214, 0, 0},
                                      {104, 0, -5, 0}, {56, 142, 0, 0},  {68, 289, 0, 0}, {22, 430, 0, 0},
                                      {61, 0, -13, 0}, {165, 283, 0, 0}, {303, 0, -18, 0}};
constexpr ExpectedGlyph kGlyphs10[] = {{10, 476, 0, 0},  {325, 142, 0, 0}, {45, 374, 0, 0},
                                       {115, 501, 0, 0}, {56, 142, 0, 0},  {41, 321, 0, 0}};
constexpr ExpectedGlyph kGlyphs11[] = {{107, 458, 0, 0}};
constexpr ExpectedGlyph kGlyphs12[] = {{326, 142, 0, 0}, {107, 458, 0, 0}};
constexpr ExpectedGlyph kGlyphs13[] = {{218, 387, 0, 0}, {253, 0, -24, 1},  {58, 142, 0, 0},  {13, 368, 0, 0},
                                       {217, 363, 0, 0}, {271, 0, -15, -2}, {299, 0, -6, 0},  {48, 318, 0, 0},
                                       {27, 287, 0, 0},  {321, 162, 0, 0},  {196, 300, 0, 0}, {296, 0, -28, 0},
                                       {260, 0, -21, 1}};
constexpr ExpectedGlyph kGlyphs14[] = {{334, 142, 0, 0}, {198, 283, 0, 0}, {271, 0, -14, -1}, {37, 377, 0, 0},
                                       {58, 142, 0, 0},  {47, 334, 0, 0},  {54, 0, -13, -4}};
constexpr ExpectedGlyph kGlyphs15[] = {{34, 380, 0, 0}, {54, 0, -10, 0}};
constexpr ExpectedGlyph kGlyphs16[] = {{35, 292, 0, 0}, {54, 0, -9, 0}};
constexpr ExpectedGlyph kGlyphs17[] = {{44, 318, 0, 0},   {56, 142, 0, 0}, {22, 430, 0, 0},  {67, 0, -13, 0},
                                       {5, 0, 0, 0},      {50, 363, 0, 0}, {326, 142, 0, 0}, {123, 485, 0, 0},
                                       {292, 0, -12, -1}, {318, 0, -7, 0}};
constexpr ExpectedGlyph kGlyphs18[] = {{27, 287, 0, 0}, {7, 0, -10, 0}, {56, 142, 0, 0}, {39, 295, 0, 0}};
constexpr ExpectedGlyph kGlyphs19[] = {{52, 332, 0, 0},  {63, 193, 0, 0}, {53, 285, 0, 0}, {56, 142, 0, 0},
                                       {39, 295, 0, 0},  {48, 318, 0, 0}, {63, 193, 0, 0}, {223, 356, 0, 0},
                                       {283, 0, -18, 0}, {53, 285, 0, 0}};
constexpr ExpectedGlyph kGlyphs20[] = {{172, 371, 0, 0}, {255, 0, -22, 1}, {58, 142, 0, 0},
                                       {221, 276, 0, 0}, {243, 121, 0, 0}, {22, 430, 0, 0},
                                       {56, 142, 0, 0},  {63, 193, 0, 0},  {49, 390, 0, 0}};
constexpr ExpectedGlyph kGlyphs21[] = {{53, 360, 0, 0}, {295, 0, -9, -6}, {318, 0, -7, 0},
                                       {39, 295, 0, 0}, {47, 334, 0, 0},  {54, 0, -13, -4}};
constexpr ExpectedGlyph kGlyphs22[] = {{48, 318, 0, 0}, {250, 90, 0, 0}, {42, 382, 0, 0}};
constexpr ExpectedGlyph kGlyphs23[] = {{48, 318, 0, 0}, {248, 104, 0, 0}};
constexpr ExpectedGlyph kGlyphs24[] = {{44, 318, 0, 0}, {12, 285, 0, 0}, {102, 202, 0, 0}};
constexpr ExpectedGlyph kGlyphs25[] = {{78, 316, 0, 0}, {85, 316, 0, 0}, {82, 316, 0, 0}, {81, 316, 0, 0}};

constexpr ExpectedShaping kExpectedShaping[] = {
    {"\xE0\xA6\x95\xE0\xA6\xB2\xE0\xA6\xAE", kGlyphs0, 3},                                      // কলম
    {"\xE0\xA6\x95\xE0\xA6\xBF", kGlyphs1, 2},                                                  // কি
    {"\xE0\xA6\x9F\xE0\xA7\x87\xE0\xA6\xB2\xE0\xA6\xBF\xE0\xA6\xAC\xE0\xA6\x87", kGlyphs2, 6},  // টেলিবই
    {"\xE0\xA6\x95\xE0\xA7\x8B", kGlyphs3, 3},                                                  // কো
    {"\xE0\xA6\x95\xE0\xA7\x8C", kGlyphs4, 3},                                                  // কৌ
    {"\xE0\xA6\xB6\xE0\xA6\x95\xE0\xA7\x81\xE0\xA6\xA8\xE0\xA7\x8D\xE0\xA6\xA4\xE0\xA6\xB2\xE0\xA6\xBE", kGlyphs5,
     7},                                                                                        // শকুন্তলা
    {"\xE0\xA6\xAA\xE0\xA7\x8D\xE0\xA6\xB0\xE0\xA6\x95\xE0\xA6\xBE\xE0\xA6\xB6", kGlyphs6, 5},  // প্রকাশ
    {"\xE0\xA6\xAC\xE0\xA6\xBF\xE0\xA6\xA6\xE0\xA7\x8D\xE0\xA6\xAF\xE0\xA6\xBE\xE0\xA6\xB8\xE0\xA6\xBE\xE0\xA6\x97\xE0"
     "\xA6\xB0",
     kGlyphs7, 9},  // বিদ্যাসাগর
    {"\xE0\xA6\x95\xE0\xA6\xB0\xE0\xA7\x8D\xE0\xA6\xA4\xE0\xA7\x8D\xE0\xA6\xA4\xE0\xA7\x83\xE0\xA6\x95", kGlyphs8,
     5},  // কর্ত্তৃক
    {"\xE0\xA6\xB8\xE0\xA6\xB0\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA7\x8B\xE0\xA7\x8E\xE0\xA6\x95\xE0"
     "\xA7\x83\xE0\xA6\xB7\xE0\xA7\x8D\xE0\xA6\x9F",
     kGlyphs9, 11},  // সর্ব্বোৎকৃষ্ট
    {"\xE0\xA6\x85\xE0\xA6\xAD\xE0\xA6\xBF\xE0\xA6\x9C\xE0\xA7\x8D\xE0\xA6\x9E\xE0\xA6\xBE\xE0\xA6\xA8", kGlyphs10,
     6},                                                                 // অভিজ্ঞান
    {"\xE0\xA6\x95\xE0\xA7\x8D\xE0\xA6\xB7", kGlyphs11, 1},              // ক্ষ
    {"\xE0\xA6\x95\xE0\xA7\x8D\xE0\xA6\xB7\xE0\xA6\xBF", kGlyphs12, 2},  // ক্ষি
    {"\xE0\xA6\xB6\xE0\xA7\x8D\xE0\xA6\xB0\xE0\xA7\x80\xE0\xA6\x88\xE0\xA6\xB6\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA6\xB0\xE0"
     "\xA6\x9A\xE0\xA6\xA8\xE0\xA7\x8D\xE0\xA6\xA6\xE0\xA7\x8D\xE0\xA6\xB0",
     kGlyphs13, 13},  // শ্রীঈশ্বরচন্দ্র
    {"\xE0\xA6\xA6\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA6\xBF\xE0\xA6\xA4\xE0\xA7\x80\xE0\xA6\xAF\xE0\xA6\xBC", kGlyphs14,
     7},                                         // দ্বিতীয়
    {"\xE0\xA6\xA1\xE0\xA6\xBC", kGlyphs15, 2},  // ড়
    {"\xE0\xA6\xA2\xE0\xA6\xBC", kGlyphs16, 2},  // ঢ়
    {"\xE0\xA6\xAC\xE0\xA6\xBE\xE0\xA6\x95\xE0\xA7\x8D\xE2\x80\x8C\xE0\xA6\xB6\xE0\xA6\x95\xE0\xA7\x8D\xE0\xA6\xA4\xE0"
     "\xA6\xBF",
     kGlyphs17, 10},                                                     // বাক্‌শক্তি
    {"\xE0\xA6\x9A\xE0\xA6\xBE\xE0\xA6\x81\xE0\xA6\xA6", kGlyphs18, 4},  // চাঁদ
    {"\xE0\xA6\xB8\xE0\xA6\xB9\xE0\xA7\x8B\xE0\xA6\xA6\xE0\xA6\xB0\xE0\xA6\xB8\xE0\xA7\x8D\xE0\xA6\xA8\xE0\xA7\x87\xE0"
     "\xA6\xB9",
     kGlyphs19, 10},  // সহোদরস্নেহ
    {"\xE0\xA6\x97\xE0\xA7\x8D\xE0\xA6\xB0\xE0\xA7\x80\xE0\xA6\xB7\xE0\xA7\x8D\xE0\xA6\xAE\xE0\xA6\x95\xE0\xA6\xBE\xE0"
     "\xA6\xB2\xE0\xA7\x87",
     kGlyphs20, 9},                                                                  // গ্রীষ্মকালে
    {"\xE0\xA6\xB9\xE0\xA7\x83\xE0\xA6\xA6\xE0\xA6\xAF\xE0\xA6\xBC", kGlyphs21, 6},  // হৃদয়
    {"\xE0\xA6\xB0\xE0\xA7\x82\xE0\xA6\xAA", kGlyphs22, 3},                          // রূপ
    {"\xE0\xA6\xB0\xE0\xA7\x81", kGlyphs23, 2},                                      // রু
    {"\xE0\xA6\xAC\xE0\xA6\x87\xE0\xA5\xA4", kGlyphs24, 3},                          // বই।
    {"\xE0\xA7\xA7\xE0\xA7\xAE\xE0\xA7\xAB\xE0\xA7\xAA", kGlyphs25, 4},              // ১৮৫৪
};
