#pragma once
// Generated by generate_fixtures.py from data/*.layout. Do not edit.

#include <cstddef>
#include <cstdint>

constexpr uint32_t kFixturePpem26_6 = 2133;

struct ExpectedGlyph {
  uint16_t gid;
  uint16_t advance12_4;
  int8_t dx;
  int8_t dy;
};

struct ExpectedShaping {
  const char* utf8;
  const char* language;  // BCP 47; "" = none
  const ExpectedGlyph* glyphs;
  uint8_t count;
};

struct ShapingFixture {
  const char* script;
  const char* layoutFile;  // in data/
  const ExpectedShaping* words;
  size_t count;
};

constexpr ExpectedGlyph kBengaliGlyphs0[] = {{22, 430, 0, 0}, {49, 390, 0, 0}, {46, 326, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs1[] = {{57, 142, 0, 0}, {22, 430, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs2[] = {{370, 193, 0, 0}, {32, 292, 0, 0}, {327, 142, 0, 0},
                                             {49, 390, 0, 0},  {44, 318, 0, 0}, {12, 285, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs3[] = {{370, 193, 0, 0}, {22, 430, 0, 0}, {56, 142, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs4[] = {{370, 193, 0, 0}, {22, 430, 0, 0}, {69, 142, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs5[] = {{50, 363, 0, 0},   {22, 430, 0, 0}, {59, 0, -13, 0}, {203, 403, 0, 0},
                                             {275, 0, -26, -2}, {49, 390, 0, 0}, {56, 142, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs6[] = {
    {206, 408, 0, 0}, {253, 0, -24, 1}, {22, 430, 0, 0}, {56, 142, 0, 0}, {50, 363, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs7[] = {{57, 142, 0, 0},  {44, 318, 0, 0}, {39, 295, 0, 0},
                                             {105, 144, 0, 0}, {56, 142, 0, 0}, {52, 332, 0, 0},
                                             {56, 142, 0, 0},  {24, 345, 0, 0}, {48, 318, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs8[] = {
    {22, 430, 0, 0}, {123, 379, 0, 0}, {61, 0, -8, 0}, {104, 0, -9, 0}, {22, 430, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs9[] = {{52, 332, 0, 0}, {63, 193, 0, 0},  {44, 318, 0, 0}, {240, 214, 0, 0},
                                             {104, 0, -5, 0}, {56, 142, 0, 0},  {68, 289, 0, 0}, {22, 430, 0, 0},
                                             {61, 0, -13, 0}, {165, 283, 0, 0}, {303, 0, -18, 0}};
constexpr ExpectedGlyph kBengaliGlyphs10[] = {{10, 476, 0, 0},  {325, 142, 0, 0}, {45, 374, 0, 0},
                                              {115, 501, 0, 0}, {56, 142, 0, 0},  {41, 321, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs11[] = {{107, 458, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs12[] = {{326, 142, 0, 0}, {107, 458, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs13[] = {{218, 387, 0, 0}, {253, 0, -24, 1},  {58, 142, 0, 0},  {13, 368, 0, 0},
                                              {217, 363, 0, 0}, {271, 0, -15, -2}, {299, 0, -6, 0},  {48, 318, 0, 0},
                                              {27, 287, 0, 0},  {321, 162, 0, 0},  {196, 300, 0, 0}, {296, 0, -28, 0},
                                              {260, 0, -21, 1}};
constexpr ExpectedGlyph kBengaliGlyphs14[] = {{334, 142, 0, 0}, {198, 283, 0, 0}, {271, 0, -14, -1}, {37, 377, 0, 0},
                                              {58, 142, 0, 0},  {47, 334, 0, 0},  {54, 0, -13, -4}};
constexpr ExpectedGlyph kBengaliGlyphs15[] = {{34, 380, 0, 0}, {54, 0, -10, 0}};
constexpr ExpectedGlyph kBengaliGlyphs16[] = {{35, 292, 0, 0}, {54, 0, -9, 0}};
constexpr ExpectedGlyph kBengaliGlyphs17[] = {{44, 318, 0, 0},   {56, 142, 0, 0}, {22, 430, 0, 0},  {67, 0, -13, 0},
                                              {5, 0, 0, 0},      {50, 363, 0, 0}, {326, 142, 0, 0}, {123, 485, 0, 0},
                                              {292, 0, -12, -1}, {318, 0, -7, 0}};
constexpr ExpectedGlyph kBengaliGlyphs18[] = {{27, 287, 0, 0}, {7, 0, -10, 0}, {56, 142, 0, 0}, {39, 295, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs19[] = {{52, 332, 0, 0},  {63, 193, 0, 0}, {53, 285, 0, 0}, {56, 142, 0, 0},
                                              {39, 295, 0, 0},  {48, 318, 0, 0}, {63, 193, 0, 0}, {223, 356, 0, 0},
                                              {283, 0, -18, 0}, {53, 285, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs20[] = {{172, 371, 0, 0}, {255, 0, -22, 1}, {58, 142, 0, 0},
                                              {221, 276, 0, 0}, {243, 121, 0, 0}, {22, 430, 0, 0},
                                              {56, 142, 0, 0},  {63, 193, 0, 0},  {49, 390, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs21[] = {{53, 360, 0, 0}, {295, 0, -9, -6}, {318, 0, -7, 0},
                                              {39, 295, 0, 0}, {47, 334, 0, 0},  {54, 0, -13, -4}};
constexpr ExpectedGlyph kBengaliGlyphs22[] = {{48, 318, 0, 0}, {250, 90, 0, 0}, {42, 382, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs23[] = {{48, 318, 0, 0}, {248, 104, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs24[] = {{44, 318, 0, 0}, {12, 285, 0, 0}, {102, 202, 0, 0}};
constexpr ExpectedGlyph kBengaliGlyphs25[] = {{78, 316, 0, 0}, {85, 316, 0, 0}, {82, 316, 0, 0}, {81, 316, 0, 0}};

constexpr ExpectedShaping kBengaliShaping[] = {
    {"\xE0\xA6\x95\xE0\xA6\xB2\xE0\xA6\xAE", "", kBengaliGlyphs0, 3},                                      // কলম
    {"\xE0\xA6\x95\xE0\xA6\xBF", "", kBengaliGlyphs1, 2},                                                  // কি
    {"\xE0\xA6\x9F\xE0\xA7\x87\xE0\xA6\xB2\xE0\xA6\xBF\xE0\xA6\xAC\xE0\xA6\x87", "", kBengaliGlyphs2, 6},  // টেলিবই
    {"\xE0\xA6\x95\xE0\xA7\x8B", "", kBengaliGlyphs3, 3},                                                  // কো
    {"\xE0\xA6\x95\xE0\xA7\x8C", "", kBengaliGlyphs4, 3},                                                  // কৌ
    {"\xE0\xA6\xB6\xE0\xA6\x95\xE0\xA7\x81\xE0\xA6\xA8\xE0\xA7\x8D\xE0\xA6\xA4\xE0\xA6\xB2\xE0\xA6\xBE", "",
     kBengaliGlyphs5, 7},                                                                                  // শকুন্তলা
    {"\xE0\xA6\xAA\xE0\xA7\x8D\xE0\xA6\xB0\xE0\xA6\x95\xE0\xA6\xBE\xE0\xA6\xB6", "", kBengaliGlyphs6, 5},  // প্রকাশ
    {"\xE0\xA6\xAC\xE0\xA6\xBF\xE0\xA6\xA6\xE0\xA7\x8D\xE0\xA6\xAF\xE0\xA6\xBE\xE0\xA6\xB8\xE0\xA6\xBE\xE0\xA6\x97\xE0"
     "\xA6\xB0",
     "", kBengaliGlyphs7, 9},  // বিদ্যাসাগর
    {"\xE0\xA6\x95\xE0\xA6\xB0\xE0\xA7\x8D\xE0\xA6\xA4\xE0\xA7\x8D\xE0\xA6\xA4\xE0\xA7\x83\xE0\xA6\x95", "",
     kBengaliGlyphs8, 5},  // কর্ত্তৃক
    {"\xE0\xA6\xB8\xE0\xA6\xB0\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA7\x8B\xE0\xA7\x8E\xE0\xA6\x95\xE0"
     "\xA7\x83\xE0\xA6\xB7\xE0\xA7\x8D\xE0\xA6\x9F",
     "", kBengaliGlyphs9, 11},  // সর্ব্বোৎকৃষ্ট
    {"\xE0\xA6\x85\xE0\xA6\xAD\xE0\xA6\xBF\xE0\xA6\x9C\xE0\xA7\x8D\xE0\xA6\x9E\xE0\xA6\xBE\xE0\xA6\xA8", "",
     kBengaliGlyphs10, 6},                                                          // অভিজ্ঞান
    {"\xE0\xA6\x95\xE0\xA7\x8D\xE0\xA6\xB7", "", kBengaliGlyphs11, 1},              // ক্ষ
    {"\xE0\xA6\x95\xE0\xA7\x8D\xE0\xA6\xB7\xE0\xA6\xBF", "", kBengaliGlyphs12, 2},  // ক্ষি
    {"\xE0\xA6\xB6\xE0\xA7\x8D\xE0\xA6\xB0\xE0\xA7\x80\xE0\xA6\x88\xE0\xA6\xB6\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA6\xB0\xE0"
     "\xA6\x9A\xE0\xA6\xA8\xE0\xA7\x8D\xE0\xA6\xA6\xE0\xA7\x8D\xE0\xA6\xB0",
     "", kBengaliGlyphs13, 13},  // শ্রীঈশ্বরচন্দ্র
    {"\xE0\xA6\xA6\xE0\xA7\x8D\xE0\xA6\xAC\xE0\xA6\xBF\xE0\xA6\xA4\xE0\xA7\x80\xE0\xA6\xAF\xE0\xA6\xBC", "",
     kBengaliGlyphs14, 7},                                  // দ্বিতীয়
    {"\xE0\xA6\xA1\xE0\xA6\xBC", "", kBengaliGlyphs15, 2},  // ড়
    {"\xE0\xA6\xA2\xE0\xA6\xBC", "", kBengaliGlyphs16, 2},  // ঢ়
    {"\xE0\xA6\xAC\xE0\xA6\xBE\xE0\xA6\x95\xE0\xA7\x8D\xE2\x80\x8C\xE0\xA6\xB6\xE0\xA6\x95\xE0\xA7\x8D\xE0\xA6\xA4\xE0"
     "\xA6\xBF",
     "", kBengaliGlyphs17, 10},                                                     // বাক্‌শক্তি
    {"\xE0\xA6\x9A\xE0\xA6\xBE\xE0\xA6\x81\xE0\xA6\xA6", "", kBengaliGlyphs18, 4},  // চাঁদ
    {"\xE0\xA6\xB8\xE0\xA6\xB9\xE0\xA7\x8B\xE0\xA6\xA6\xE0\xA6\xB0\xE0\xA6\xB8\xE0\xA7\x8D\xE0\xA6\xA8\xE0\xA7\x87\xE0"
     "\xA6\xB9",
     "", kBengaliGlyphs19, 10},  // সহোদরস্নেহ
    {"\xE0\xA6\x97\xE0\xA7\x8D\xE0\xA6\xB0\xE0\xA7\x80\xE0\xA6\xB7\xE0\xA7\x8D\xE0\xA6\xAE\xE0\xA6\x95\xE0\xA6\xBE\xE0"
     "\xA6\xB2\xE0\xA7\x87",
     "", kBengaliGlyphs20, 9},                                                                  // গ্রীষ্মকালে
    {"\xE0\xA6\xB9\xE0\xA7\x83\xE0\xA6\xA6\xE0\xA6\xAF\xE0\xA6\xBC", "", kBengaliGlyphs21, 6},  // হৃদয়
    {"\xE0\xA6\xB0\xE0\xA7\x82\xE0\xA6\xAA", "", kBengaliGlyphs22, 3},                          // রূপ
    {"\xE0\xA6\xB0\xE0\xA7\x81", "", kBengaliGlyphs23, 2},                                      // রু
    {"\xE0\xA6\xAC\xE0\xA6\x87\xE0\xA5\xA4", "", kBengaliGlyphs24, 3},                          // বই।
    {"\xE0\xA7\xA7\xE0\xA7\xAE\xE0\xA7\xAB\xE0\xA7\xAA", "", kBengaliGlyphs25, 4},              // ১৮৫৪
};

constexpr ExpectedGlyph kDevanagariGlyphs0[] = {
    {446, 138, 0, 0}, {84, 283, 0, 0}, {150, 165, 0, 0}, {69, 283, 0, 0}, {29, 138, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs1[] = {
    {72, 303, 0, 0}, {447, 138, 0, 0}, {209, 294, 0, 0}, {52, 410, 0, 0}, {27, 138, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs2[] = {{222, 378, 0, 0}, {29, 138, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs3[] = {{214, 304, 0, 0}, {27, 138, 0, 0}, {68, 341, 0, 0},
                                                {408, 0, 0, 0},   {71, 296, 0, 0}, {27, 138, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs4[] = {{52, 410, 0, 0}, {32, 0, -7, 0}, {160, 172, 0, 0}, {66, 386, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs5[] = {{87, 342, 0, 0}, {27, 138, 0, 0}, {71, 296, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs6[] = {{350, 426, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs7[] = {{272, 161, 0, 0}, {77, 309, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs8[] = {{447, 138, 0, 0}, {126, 410, 0, 0}, {79, 362, 0, 0}, {27, 138, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs9[] = {{409, 165, 0, 0}, {77, 309, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs10[] = {{83, 361, 0, 0}, {96, 0, 0, 0},   {161, 208, 0, 0}, {52, 410, 0, 0},
                                                 {32, 0, -7, 0},  {67, 304, 0, 0}, {76, 319, 0, 0},  {99, 0, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs11[] = {{79, 362, 0, 0}, {86, 382, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs12[] = {{380, 373, 0, 0}, {86, 382, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs13[] = {{60, 403, 0, 0}, {27, 138, 0, 0}, {64, 285, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs14[] = {{95, 493, 0, 0}, {27, 138, 0, 0}, {64, 285, 0, 0}};
constexpr ExpectedGlyph kDevanagariGlyphs15[] = {{118, 277, 0, 0}, {120, 277, 0, 0}, {119, 277, 0, 0}};

constexpr ExpectedShaping kDevanagariShaping[] = {
    {"\xE0\xA4\xB9\xE0\xA4\xBF\xE0\xA4\xA8\xE0\xA5\x8D\xE0\xA4\xA6\xE0\xA5\x80", "", kDevanagariGlyphs0, 5},  // हिन्दी
    {"\xE0\xA4\xAA\xE0\xA4\xA4\xE0\xA5\x8D\xE0\xA4\xB0\xE0\xA4\xBF\xE0\xA4\x95\xE0\xA4\xBE", "", kDevanagariGlyphs1,
     5},                                                                              // पत्रिका
    {"\xE0\xA4\xB6\xE0\xA5\x8D\xE0\xA4\xB0\xE0\xA5\x80", "", kDevanagariGlyphs2, 2},  // श्री
    {"\xE0\xA4\xAA\xE0\xA5\x8D\xE0\xA4\xB0\xE0\xA4\xBE\xE0\xA4\xB0\xE0\xA5\x8D\xE0\xA4\xA5\xE0\xA4\xA8\xE0\xA4\xBE", "",
     kDevanagariGlyphs3, 6},                                                                      // प्रार्थना
    {"\xE0\xA4\x95\xE0\xA5\x83\xE0\xA4\xB7\xE0\xA5\x8D\xE0\xA4\xA3", "", kDevanagariGlyphs4, 4},  // कृष्ण
    {"\xE0\xA4\x9C\xE0\xA5\x8D\xE0\xA4\x9E\xE0\xA4\xBE\xE0\xA4\xA8", "", kDevanagariGlyphs5, 3},  // ज्ञान
    {"\xE0\xA4\xA6\xE0\xA5\x8D\xE0\xA4\xA7", "", kDevanagariGlyphs6, 1},                          // द्ध
    {"\xE0\xA4\xA4\xE0\xA5\x8D\xE0\xA4\xB0\xE0\xA5\x8D\xE0\xA4\xAF", "", kDevanagariGlyphs7, 2},  // त्र्य
    {"\xE0\xA4\x95\xE0\xA4\xBC\xE0\xA4\xBF\xE0\xA4\xB2\xE0\xA4\xBE", "", kDevanagariGlyphs8, 4},  // क़िला
    {"\xE0\xA4\xB0\xE0\xA5\x8D\xE2\x80\x8D\xE0\xA4\xAF", "", kDevanagariGlyphs9, 2},              // र्‍य
    {"\xE0\xA4\xB8\xE0\xA4\x82\xE0\xA4\xB8\xE0\xA5\x8D\xE0\xA4\x95\xE0\xA5\x83\xE0\xA4\xA4\xE0\xA4\xAE\xE0\xA5\x8D", "",
     kDevanagariGlyphs10, 8},                                                            // संस्कृतम्
    {"\xE0\xA4\xB2\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA4\xB7", "", kDevanagariGlyphs11, 2},    // लक्ष
    {"\xE0\xA4\xB2\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA4\xB7", "mr", kDevanagariGlyphs12, 2},  // लक्ष (mr)
    {"\xE0\xA4\x9D\xE0\xA4\xBE\xE0\xA4\xA1", "", kDevanagariGlyphs13, 3},                // झाड
    {"\xE0\xA4\x9D\xE0\xA4\xBE\xE0\xA4\xA1", "ne", kDevanagariGlyphs14, 3},              // झाड (ne)
    {"\xE0\xA5\xAF\xE0\xA5\xAE\xE0\xA5\xAB", "ne", kDevanagariGlyphs15, 3},              // ९८५ (ne)
};

constexpr ExpectedGlyph kTamilGlyphs0[] = {{23, 440, 0, 0}, {27, 458, 0, 0}, {40, 140, 0, 0}, {92, 458, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs1[] = {{44, 481, 0, 0}, {16, 440, 0, 0}, {39, 341, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs2[] = {{45, 384, 0, 0}, {16, 440, 0, 0}, {39, 341, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs3[] = {{44, 481, 0, 0}, {16, 440, 0, 0}, {52, 571, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs4[] = {{74, 987, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs5[] = {{161, 807, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs6[] = {{44, 481, 0, 0}, {26, 415, 0, 0},  {39, 325, 0, 0},
                                           {84, 642, 0, 0}, {25, 658, 0, 0},  {40, 140, 0, 0},
                                           {28, 514, 0, 0}, {163, 140, 0, 0}, {84, 658, 0, 0}};
constexpr ExpectedGlyph kTamilGlyphs7[] = {
    {44, 481, 0, 0}, {18, 386, 0, 0}, {90, 540, 0, 0}, {34, 557, 0, 0}, {84, 658, 0, 0}};

constexpr ExpectedShaping kTamilShaping[] = {
    {"\xE0\xAE\xA4\xE0\xAE\xAE\xE0\xAE\xBF\xE0\xAE\xB4\xE0\xAF\x8D", "", kTamilGlyphs0, 4},  // தமிழ்
    {"\xE0\xAE\x95\xE0\xAF\x8A", "", kTamilGlyphs1, 3},                                      // கொ
    {"\xE0\xAE\x95\xE0\xAF\x8B", "", kTamilGlyphs2, 3},                                      // கோ
    {"\xE0\xAE\x95\xE0\xAF\x8C", "", kTamilGlyphs3, 3},                                      // கௌ
    {"\xE0\xAE\x95\xE0\xAF\x8D\xE0\xAE\xB7", "", kTamilGlyphs4, 1},                          // க்ஷ
    {"\xE0\xAE\xB8\xE0\xAF\x8D\xE0\xAE\xB0\xE0\xAF\x80", "", kTamilGlyphs5, 1},              // ஸ்ரீ
    {"\xE0\xAE\xAA\xE0\xAF\x8A\xE0\xAE\xA9\xE0\xAF\x8D\xE0\xAE\xA9\xE0\xAE\xBF\xE0\xAE\xAF\xE0\xAE\xBF\xE0\xAE\xA9\xE0"
     "\xAF\x8D",
     "", kTamilGlyphs6, 9},  // பொன்னியின்
    {"\xE0\xAE\x9A\xE0\xAF\x86\xE0\xAE\xB2\xE0\xAF\x8D\xE0\xAE\xB5\xE0\xAE\xA9\xE0\xAF\x8D", "", kTamilGlyphs7,
     5},  // செல்வன்
};

constexpr ExpectedGlyph kSinhalaGlyphs0[] = {
    {57, 479, 0, 0}, {82, 0, -24, 0}, {61, 251, 0, 0}, {58, 517, 0, 0}, {53, 454, 0, 0}};
constexpr ExpectedGlyph kSinhalaGlyphs1[] = {{55, 488, 0, 0}, {127, 0, -29, 0}, {93, 0, -25, 0}};
constexpr ExpectedGlyph kSinhalaGlyphs2[] = {{64, 759, 0, 0}};
constexpr ExpectedGlyph kSinhalaGlyphs3[] = {{111, 337, 0, 0}, {20, 537, 0, 0}, {130, 183, 0, 0}};
constexpr ExpectedGlyph kSinhalaGlyphs4[] = {{111, 337, 0, 0}, {20, 537, 0, 0}, {117, 279, 0, 0}};
constexpr ExpectedGlyph kSinhalaGlyphs5[] = {
    {53, 454, 0, 0}, {61, 251, 0, 0}, {20, 537, 0, 0}, {79, 180, 0, 0}, {54, 442, 0, 0}};

constexpr ExpectedShaping kSinhalaShaping[] = {
    {"\xE0\xB7\x83\xE0\xB7\x92\xE0\xB6\x82\xE0\xB7\x84\xE0\xB6\xBD", "", kSinhalaGlyphs0, 5},  // සිංහල
    {"\xE0\xB7\x81\xE0\xB7\x8A\xE2\x80\x8D\xE0\xB6\xBB\xE0\xB7\x93", "", kSinhalaGlyphs1, 3},  // ශ්‍රී
    {"\xE0\xB6\x9A\xE0\xB7\x8A\xE2\x80\x8D\xE0\xB7\x82", "", kSinhalaGlyphs2, 1},              // ක්‍ෂ
    {"\xE0\xB6\x9A\xE0\xB7\x9D", "", kSinhalaGlyphs3, 3},                                      // කෝ
    {"\xE0\xB6\x9A\xE0\xB7\x9E", "", kSinhalaGlyphs4, 3},                                      // කෞ
    {"\xE0\xB6\xBD\xE0\xB6\x82\xE0\xB6\x9A\xE0\xB7\x8F\xE0\xB7\x80", "", kSinhalaGlyphs5, 5},  // ලංකාව
};

constexpr ShapingFixture kShapingFixtures[] = {
    {"Bengali", "NotoSansBengali-Regular.layout", kBengaliShaping,
     sizeof(kBengaliShaping) / sizeof(kBengaliShaping[0])},
    {"Devanagari", "NotoSansDevanagari-Regular.layout", kDevanagariShaping,
     sizeof(kDevanagariShaping) / sizeof(kDevanagariShaping[0])},
    {"Tamil", "NotoSansTamil-Regular.layout", kTamilShaping, sizeof(kTamilShaping) / sizeof(kTamilShaping[0])},
    {"Sinhala", "NotoSansSinhala-Regular.layout", kSinhalaShaping,
     sizeof(kSinhalaShaping) / sizeof(kSinhalaShaping[0])},
};
