#!/usr/bin/env python3
"""Regenerate the ComplexShaper test fixtures.

Writes data/NotoSansBengali-Regular.layout (the layout blob the .cpfont
converter embeds, built by lib/EpdFont/scripts/shaping_blob.py) and
ExpectedShaping.h (HarfBuzz's own output for that blob, via uharfbuzz), so the
test checks that the firmware's HarfBuzz build and token encoding reproduce
reference shaping exactly.

    pip install fonttools uharfbuzz
    python3 test/complex_shaper/generate_fixtures.py NotoSansBengali-Regular.ttf

Noto Sans Bengali: https://github.com/notofonts/bengali (SIL OFL 1.1, see
data/OFL.txt).
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / "lib" / "EpdFont" / "scripts"))

import shaping_blob  # noqa: E402
import uharfbuzz as hb  # noqa: E402

# 16 pt at 150 DPI in 26.6, as the converter and TtfEpdFont compute it.
PPEM_26_6 = (16 * 150 * 64 + 36) // 72

WORDS = [
    "কলম",            # no shaping beyond cmap
    "কি",             # pre-base i-matra
    "টেলিবই",          # e-matra and i-matra in one word
    "কো", "কৌ",        # two-part vowels
    "শকুন্তলা",         # n-ta conjunct and u below a base
    "প্রকাশ",           # ra-phala
    "বিদ্যাসাগর",        # ya-phala with i-matra before the cluster
    "কর্ত্তৃক",           # reph over a doubled conjunct with ri-matra
    "সর্ব্বোৎকৃষ্ট",        # reph, o-matra, khanda ta, ss-tta
    "অভিজ্ঞান",          # j-nya
    "ক্ষ", "ক্ষি",        # k-ssa with and without a matra
    "শ্রীঈশ্বরচন্দ্র",      # ra-phala, ba-phala, ndra
    "দ্বিতীয়",           # decomposed ya + nukta
    "ড়", "ঢ়",          # nukta letters
    "বাক্‌শক্তি",         # ZWNJ keeps the halant explicit
    "চাঁদ",            # candrabindu
    "সহোদরস্নেহ",        # s-n conjunct under e-matra
    "গ্রীষ্মকালে",        # ra-phala, ss-ma
    "হৃদয়", "রূপ", "রু",  # special u/uu/ri forms under ha and ra
    "বই।",            # danda joins the run
    "১৮৫৪",           # Bengali digits
]


def main():
    font_path = sys.argv[1]
    _, layout, _ = shaping_blob.build(font_path, ["bengali"])
    (HERE / "data" / "NotoSansBengali-Regular.layout").write_bytes(layout)

    font = hb.Font(hb.Face(layout))
    font.scale = (PPEM_26_6, PPEM_26_6)
    font.ppem = ((PPEM_26_6 + 32) >> 6,) * 2

    def round_px(v):
        return (v + 32) // 64 if v >= 0 else -((-v + 32) // 64)

    lines = [
        "#pragma once",
        "// Generated by generate_fixtures.py from data/NotoSansBengali-Regular.layout. Do not edit.",
        "",
        "#include <cstdint>",
        "",
        f"constexpr uint32_t kFixturePpem26_6 = {PPEM_26_6};",
        "",
        "struct ExpectedGlyph {",
        "  uint16_t gid;",
        "  uint16_t advance12_4;",
        "  int8_t dx;",
        "  int8_t dy;",
        "};",
        "",
        "struct ExpectedShaping {",
        "  const char* utf8;",
        "  const ExpectedGlyph* glyphs;",
        "  uint8_t count;",
        "};",
        "",
    ]
    table = []
    for i, word in enumerate(WORDS):
        buf = hb.Buffer()
        buf.add_str(word)
        buf.direction = "ltr"
        buf.script = "Beng"
        buf.language = "bn"
        hb.shape(font, buf, {})
        glyphs = [
            f"{{{info.codepoint}, {(pos.x_advance + 2) >> 2}, {round_px(pos.x_offset)}, {-round_px(pos.y_offset)}}}"
            for info, pos in zip(buf.glyph_infos, buf.glyph_positions)
        ]
        lines.append(f"constexpr ExpectedGlyph kGlyphs{i}[] = {{{', '.join(glyphs)}}};")
        escaped = "".join(c if ord(c) < 0x80 else "".join(f"\\x{b:02X}" for b in c.encode()) for c in word)
        table.append(f'    {{"{escaped}", kGlyphs{i}, {len(glyphs)}}},  // {word}')
    lines += ["", "constexpr ExpectedShaping kExpectedShaping[] = {", *table, "};", ""]
    (HERE / "ExpectedShaping.h").write_text("\n".join(lines))
    print(f"layout blob: {len(layout)} bytes, {len(WORDS)} expected words")


if __name__ == "__main__":
    main()
