#pragma once
#include <string>

#include "I18nKeys.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.

namespace i18n_strings {

extern const char* const STRINGS_EN[];
extern const char* const STRINGS_SP[];
extern const char* const STRINGS_IT[];
extern const char* const STRINGS_SW[];
extern const char* const STRINGS_FR[];
extern const char* const STRINGS_DE[];
extern const char* const STRINGS_CZ[];

}  // namespace i18n_strings
