#include "I18nStrings.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.

// Language display names
const char* const LANGUAGE_NAMES[] = {
    "English",
    "Espa\xC3"
    "\xB1"
    "ol (placeholder)",
    "Italiano (placeholder)",
    "Svenska (placeholder)",
    "Fran\xC3"
    "\xA7"
    "ais",
    "Deutsch",
    "\xC4"
    "\x8C"
    "e\xC5"
    "\xA1"
    "tina",
};

// Character sets for each language
const char* const CHARACTER_SETS[] = {
    " !\"%'()*+,-./012345:=?ABCDEFGHIJKLMNOPQRSTUVWXY[\\]abcdefghijklmnopqrstuvwxyz|\xC2"
    "\xAB"
    "",  // English
    " !\"%'()*+,-./012345:=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]dfsuz|\xC2"
    "\xAB"
    "",  // Español (placeholder)
    " !\"%'()*+,-./012345:=?ABCDEFGHIJKLMNOPQRSTUVWXY[\\]abcdefghijklmnopqrstuvwxyz|\xC2"
    "\xAB"
    "",  // Italiano (placeholder)
    " !\"%'()*+,-./012345:=?ABCDEFGHIJKLMNOPQRSTUVWXY[\\]abcdefghijklmnopqrstuvwxyz|\xC2"
    "\xAB"
    "",  // Svenska (placeholder)
    " !%()*+,-./012345:=?ABCDEFGHIJKLMNOPQRSTUVWX[\\]abcdefghijklmnopqrstuvwxyz|\xC2"
    "\xAB"
    "\xC3"
    "\x89"
    "\xC3"
    "\xA0"
    "\xC3"
    "\xA7"
    "\xC3"
    "\xA8"
    "\xC3"
    "\xA9"
    "\xC3"
    "\xAA"
    "\xC3"
    "\xAE"
    "\xC3"
    "\xB4"
    "\xE2"
    "\x80"
    "\x98"
    "\xE2"
    "\x80"
    "\x99"
    "\xE2"
    "\x80"
    "\x9C"
    "\xE2"
    "\x80"
    "\x9D"
    "\xE2"
    "\x80"
    "\xA6"
    "",  // Français
    " !\"%&'()*+,-./012345:=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]abcdefghiklmnoprstuvwxyz|\xC2"
    "\xAB"
    "\xC3"
    "\x84"
    "\xC3"
    "\x96"
    "\xC3"
    "\x9C"
    "\xC3"
    "\x9F"
    "\xC3"
    "\xA4"
    "\xC3"
    "\xB6"
    "\xC3"
    "\xBC"
    "\xE2"
    "\x80"
    "\xA6"
    "",  // Deutsch
    " !%()*+,-./012345:=?ABCDEFHIJKLMNOPQRSTUVWXYZ[\\]abcdefghijklmnoprstuvwxyz|\xC2"
    "\xAB"
    "\xC3"
    "\x81"
    "\xC3"
    "\x8D"
    "\xC3"
    "\x9A"
    "\xC3"
    "\xA1"
    "\xC3"
    "\xA9"
    "\xC3"
    "\xAD"
    "\xC3"
    "\xB3"
    "\xC3"
    "\xBA"
    "\xC3"
    "\xBD"
    "\xC4"
    "\x8C"
    "\xC4"
    "\x8D"
    "\xC4"
    "\x8F"
    "\xC4"
    "\x9A"
    "\xC4"
    "\x9B"
    "\xC5"
    "\x98"
    "\xC5"
    "\x99"
    "\xC5"
    "\xA0"
    "\xC5"
    "\xA1"
    "\xC5"
    "\xA5"
    "\xC5"
    "\xAF"
    "\xC5"
    "\xBD"
    "\xC5"
    "\xBE"
    "\xE2"
    "\x80"
    "\x9C"
    "\xE2"
    "\x80"
    "\x9E"
    "\xE2"
    "\x80"
    "\xA6"
    "",  // Čeština
};

namespace i18n_strings {

const char* const STRINGS_EN[] = {
    "CrossPoint",
    "BOOTING",
    "SLEEPING",
    "Entering Sleep...",
    "Browse Files",
    "File Transfer",
    "Settings",
    "Calibre Library",
    "Continue Reading",
    "No open book",
    "Start reading below",
    "Books",
    "No books found",
    "Select Chapter",
    "No chapters",
    "End of book",
    "Empty chapter",
    "Indexing...",
    "Memory error",
    "Page load error",
    "Empty file",
    "Out of bounds",
    "Loading...",
    "Failed to load XTC",
    "Failed to load TXT",
    "Failed to load EPUB",
    "SD card error",
    "WiFi Networks",
    "No networks found",
    "%zu networks found",
    "Scanning...",
    "Connecting...",
    "Connected!",
    "Connection Failed",
    "Connection timeout",
    "Forget Network?",
    "Save password for next time?",
    "Remove saved password?",
    "Press OK to scan again",
    "Press any button to continue",
    "LEFT/RIGHT: Select | OK: Confirm",
    "How would you like to connect?",
    "Join a Network",
    "Create Hotspot",
    "Connect to an existing WiFi network",
    "Create a WiFi network others can join",
    "Starting Hotspot...",
    "Hotspot Mode",
    "Connect your device to this WiFi network",
    "Open this URL in your browser",
    "or http://",
    "or scan QR code with your phone:",
    "Calibre Wireless",
    "Calibre Web URL",
    "Connect as Wireless Device",
    "* = Encrypted | + = Saved",
    "MAC address:",
    "Checking WiFi...",
    "Enter WiFi Password",
    "Enter Text",
    "to ",
    "Discovering Calibre...",
    "Connecting to ",
    "Connected to ",
    "Waiting for commands...",
    "(Connection failed, retrying)",
    "Calibre disconnected",
    "Waiting for transfer...",
    "If transfer fails, enable\n'Ignore free space' in Calibre's\nSmartDevice plugin settings.",
    "Receiving: ",
    "Received: ",
    "Waiting for more...",
    "Failed to create file",
    "Password required",
    "Transfer interrupted",
    "1) Install CrossPoint Reader plugin",
    "2) Be on the same WiFi network",
    "3) In Calibre: \"Send to device\"",
    "\"Keep this screen open while sending\"",
    "Display",
    "Reader",
    "Controls",
    "System",
    "Sleep Screen",
    "Sleep Screen Cover Mode",
    "Status Bar",
    "Hide Battery %",
    "Extra Paragraph Spacing",
    "Text Anti-Aliasing",
    "Short Power Button Click",
    "Reading Orientation",
    "Front Button Layout",
    "Side Button Layout (reader)",
    "Long-press Chapter Skip",
    "Reader Font Family",
    "External Reader Font",
    "Reader Font",
    "UI Font",
    "UI Font Size",
    "Reader Line Spacing",
    "ASCII Letter Spacing",
    "ASCII Digit Spacing",
    "CJK Spacing",
    "Color Mode",
    "Reader Screen Margin",
    "Reader Paragraph Alignment",
    "Hyphenation",
    "Time to Sleep",
    "Refresh Frequency",
    "Calibre Settings",
    "KOReader Sync",
    "Check for updates",
    "Language",
    "Select Wallpaper",
    "Clear Reading Cache",
    "Calibre",
    "Username",
    "Password",
    "Sync Server URL",
    "Document Matching",
    "Authenticate",
    "KOReader Username",
    "KOReader Password",
    "Filename",
    "Binary",
    "Set credentials first",
    "WiFi connection failed",
    "Authenticating...",
    "Successfully authenticated!",
    "KOReader Auth",
    "KOReader sync is ready to use",
    "Authentication Failed",
    "Done",
    "This will clear all cached book data.",
    "All reading progress will be lost!",
    "Books will need to be re-indexed",
    "when opened again.",
    "Clearing cache...",
    "Cache Cleared",
    "items removed",
    "failed",
    "Failed to clear cache",
    "Check serial output for details",
    "Dark",
    "Light",
    "Custom",
    "Cover",
    "None",
    "Fit",
    "Crop",
    "No Progress",
    "Full",
    "Never",
    "In Reader",
    "Always",
    "Ignore",
    "Sleep",
    "Page Turn",
    "Portrait",
    "Landscape CW",
    "Inverted",
    "Landscape CCW",
    "Bck, Cnfrm, Lft, Rght",
    "Lft, Rght, Bck, Cnfrm",
    "Lft, Bck, Cnfrm, Rght",
    "Prev/Next",
    "Next/Prev",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Small",
    "Medium",
    "Large",
    "X Large",
    "Tight",
    "Normal",
    "Wide",
    "Justify",
    "Left",
    "Center",
    "Right",
    "1 min",
    "5 min",
    "10 min",
    "15 min",
    "30 min",
    "1 page",
    "5 pages",
    "10 pages",
    "15 pages",
    "30 pages",
    "Update",
    "Checking for update...",
    "New update available!",
    "Current Version: ",
    "New Version: ",
    "Updating...",
    "No update available",
    "Update failed",
    "Update complete",
    "Press and hold power button to turn back on",
    "External Font",
    "Built-in (Disabled)",
    "No entries found",
    "Downloading...",
    "Download failed",
    "Error:",
    "Unnamed",
    "No server URL configured",
    "Failed to fetch feed",
    "Failed to parse feed",
    "Network: ",
    "IP Address: ",
    "or scan QR code with your phone to connect to Wifi.",
    "Error: General failure",
    "Error: Network not found",
    "Error: Connection timeout",
    "SD card",
    "\xC2"
    "\xAB"
    " Back",
    "\xC2"
    "\xAB"
    " Exit",
    "\xC2"
    "\xAB"
    " Home",
    "\xC2"
    "\xAB"
    " Save",
    "Select",
    "Toggle",
    "Confirm",
    "Cancel",
    "Connect",
    "Open",
    "Download",
    "Retry",
    "Yes",
    "No",
    "ON",
    "OFF",
    "Set",
    "Not Set",
    "Left",
    "Right",
    "Up",
    "Down",
    "CAPS",
    "caps",
    "OK",
    "[ON]",
    "Sleep Screen Cover Filter",
    "Contrast",
    "Full w/ Percentage",
    "Full w/ Book Bar",
    "Book Bar Only",
    "Full w/ Chapter Bar",
    "UI Theme",
    "Classic",
    "Lyra",
    "Sunlight Fading Fix",
    "Remap Front Buttons",
    "OPDS Browser",
    "Cover + Custom",
    "Recents",
    "Recent Books",
    "No recent books",
    "Use Calibre wireless device transfers",
    "Forget network and remove saved password?",
    "Forget network",
    "Starting Calibre...",
    "Setup",
    "Status",
    "Clear",
    "Default",
    "Press a front button for each role",
    "Unassigned",
    "Already assigned",
    "Side button Up: Reset to default layout",
    "Side button Down: Cancel remapping",
    "Back (1st button)",
    "Confirm (2nd button)",
    "Left (3rd button)",
    "Right (4th button)",
    "Go to %",
    "Go Home",
    "Sync Progress",
    "Delete Book Cache",
    "Chapter: ",
    " pages  |  ",
    "Book: ",
    "shift",
    "SHIFT",
    "LOCK",
    "For Calibre, add /opds to your URL",
    "Left/Right: 1%  Up/Down: 10%",
    "Syncing time...",
    "Calculating document hash...",
    "Failed to calculate document hash",
    "Fetching remote progress...",
    "Uploading progress...",
    "No credentials configured",
    "Set up KOReader account in Settings",
    "Progress found!",
    "Remote:",
    "Local:",
    "Page %d, %.2f%% overall",
    "Page %d/%d, %.2f%% overall",
    "  From: %s",
    "Apply remote progress",
    "Upload local progress",
    "No remote progress found",
    "Upload current position?",
    "Progress uploaded!",
    "Sync failed",
    "Section ",
    "Upload",
    "Book's Style",
    "Embedded Style",
    "OPDS Server URL",
};

const char* const STRINGS_SP[] = {
    "CROSSPOINT",
    "BOOTING",
    "SLEEPING",
    "ENTERING SLEEP...",
    "BROWSE FILES",
    "FILE TRANSFER",
    "SETTINGS",
    "CALIBRE LIBRARY",
    "CONTINUE READING",
    "NO OPEN BOOK",
    "START READING BELOW",
    "BOOKS",
    "NO BOOKS FOUND",
    "SELECT CHAPTER",
    "NO CHAPTERS",
    "END OF BOOK",
    "EMPTY CHAPTER",
    "INDEXING...",
    "MEMORY ERROR",
    "PAGE LOAD ERROR",
    "EMPTY FILE",
    "OUT OF BOUNDS",
    "LOADING...",
    "FAILED TO LOAD XTC",
    "FAILED TO LOAD TXT",
    "FAILED TO LOAD EPUB",
    "SD CARD ERROR",
    "WIFI NETWORKS",
    "NO NETWORKS FOUND",
    "%zu NETWORKS FOUND",
    "SCANNING...",
    "CONNECTING...",
    "CONNECTED!",
    "CONNECTION FAILED",
    "CONNECTION TIMEOUT",
    "FORGET NETWORK?",
    "SAVE PASSWORD FOR NEXT TIME?",
    "REMOVE SAVED PASSWORD?",
    "PRESS OK TO SCAN AGAIN",
    "PRESS ANY BUTTON TO CONTINUE",
    "LEFT/RIGHT: SELECT | OK: CONFIRM",
    "HOW WOULD YOU LIKE TO CONNECT?",
    "JOIN A NETWORK",
    "CREATE HOTSPOT",
    "CONNECT TO AN EXISTING WIFI NETWORK",
    "CREATE A WIFI NETWORK OTHERS CAN JOIN",
    "STARTING HOTSPOT...",
    "HOTSPOT MODE",
    "CONNECT YOUR DEVICE TO THIS WIFI NETWORK",
    "OPEN THIS URL IN YOUR BROWSER",
    "OR HTTP://",
    "OR SCAN QR CODE WITH YOUR PHONE:",
    "CALIBRE WIRELESS",
    "CALIBRE WEB URL",
    "CONNECT AS WIRELESS DEVICE",
    "* = ENCRYPTED | + = SAVED",
    "MAC ADDRESS:",
    "CHECKING WIFI...",
    "ENTER WIFI PASSWORD",
    "ENTER TEXT",
    "TO ",
    "DISCOVERING CALIBRE...",
    "CONNECTING TO ",
    "CONNECTED TO ",
    "WAITING FOR COMMANDS...",
    "(CONNECTION FAILED, RETRYING)",
    "CALIBRE DISCONNECTED",
    "WAITING FOR TRANSFER...",
    "IF TRANSFER FAILS, ENABLE\\N'IGNORE FREE SPACE' IN CALIBRE'S\\NSMARTDEVICE PLUGIN SETTINGS.",
    "RECEIVING: ",
    "RECEIVED: ",
    "WAITING FOR MORE...",
    "FAILED TO CREATE FILE",
    "PASSWORD REQUIRED",
    "TRANSFER INTERRUPTED",
    "1) INSTALL CROSSPOINT READER PLUGIN",
    "2) BE ON THE SAME WIFI NETWORK",
    "3) IN CALIBRE: \"SEND TO DEVICE\"",
    "\"KEEP THIS SCREEN OPEN WHILE SENDING\"",
    "DISPLAY",
    "READER",
    "CONTROLS",
    "SYSTEM",
    "SLEEP SCREEN",
    "SLEEP SCREEN COVER MODE",
    "STATUS BAR",
    "HIDE BATTERY %",
    "EXTRA PARAGRAPH SPACING",
    "TEXT ANTI-ALIASING",
    "SHORT POWER BUTTON CLICK",
    "READING ORIENTATION",
    "FRONT BUTTON LAYOUT",
    "SIDE BUTTON LAYOUT (READER)",
    "LONG-PRESS CHAPTER SKIP",
    "READER FONT FAMILY",
    "EXTERNAL READER FONT",
    "READER FONT",
    "UI FONT",
    "UI FONT SIZE",
    "READER LINE SPACING",
    "ASCII LETTER SPACING",
    "ASCII DIGIT SPACING",
    "CJK SPACING",
    "COLOR MODE",
    "READER SCREEN MARGIN",
    "READER PARAGRAPH ALIGNMENT",
    "HYPHENATION",
    "TIME TO SLEEP",
    "REFRESH FREQUENCY",
    "CALIBRE SETTINGS",
    "KOREADER SYNC",
    "CHECK FOR UPDATES",
    "LANGUAGE",
    "SELECT WALLPAPER",
    "CLEAR READING CACHE",
    "CALIBRE",
    "USERNAME",
    "PASSWORD",
    "SYNC SERVER URL",
    "DOCUMENT MATCHING",
    "AUTHENTICATE",
    "KOREADER USERNAME",
    "KOREADER PASSWORD",
    "FILENAME",
    "BINARY",
    "SET CREDENTIALS FIRST",
    "WIFI CONNECTION FAILED",
    "AUTHENTICATING...",
    "SUCCESSFULLY AUTHENTICATED!",
    "KOREADER AUTH",
    "KOREADER SYNC IS READY TO USE",
    "AUTHENTICATION FAILED",
    "DONE",
    "THIS WILL CLEAR ALL CACHED BOOK DATA.",
    "ALL READING PROGRESS WILL BE LOST!",
    "BOOKS WILL NEED TO BE RE-INDEXED",
    "WHEN OPENED AGAIN.",
    "CLEARING CACHE...",
    "CACHE CLEARED",
    "ITEMS REMOVED",
    "FAILED",
    "FAILED TO CLEAR CACHE",
    "CHECK SERIAL OUTPUT FOR DETAILS",
    "DARK",
    "LIGHT",
    "CUSTOM",
    "COVER",
    "NONE",
    "FIT",
    "CROP",
    "NO PROGRESS",
    "FULL",
    "NEVER",
    "IN READER",
    "ALWAYS",
    "IGNORE",
    "SLEEP",
    "PAGE TURN",
    "PORTRAIT",
    "LANDSCAPE CW",
    "INVERTED",
    "LANDSCAPE CCW",
    "BCK, CNFRM, LFT, RGHT",
    "LFT, RGHT, BCK, CNFRM",
    "LFT, BCK, CNFRM, RGHT",
    "PREV/NEXT",
    "NEXT/PREV",
    "BOOKERLY",
    "NOTO SANS",
    "OPEN DYSLEXIC",
    "SMALL",
    "MEDIUM",
    "LARGE",
    "X LARGE",
    "TIGHT",
    "NORMAL",
    "WIDE",
    "JUSTIFY",
    "LEFT",
    "CENTER",
    "RIGHT",
    "1 MIN",
    "5 MIN",
    "10 MIN",
    "15 MIN",
    "30 MIN",
    "1 PAGE",
    "5 PAGES",
    "10 PAGES",
    "15 PAGES",
    "30 PAGES",
    "UPDATE",
    "CHECKING FOR UPDATE...",
    "NEW UPDATE AVAILABLE!",
    "CURRENT VERSION: ",
    "NEW VERSION: ",
    "UPDATING...",
    "NO UPDATE AVAILABLE",
    "UPDATE FAILED",
    "UPDATE COMPLETE",
    "PRESS AND HOLD POWER BUTTON TO TURN BACK ON",
    "EXTERNAL FONT",
    "BUILT-IN (DISABLED)",
    "NO ENTRIES FOUND",
    "DOWNLOADING...",
    "DOWNLOAD FAILED",
    "ERROR",
    "UNNAMED",
    "NO SERVER URL CONFIGURED",
    "FAILED TO FETCH FEED",
    "FAILED TO PARSE FEED",
    "NETWORK: ",
    "IP ADDRESS: ",
    "OR SCAN QR CODE WITH YOUR PHONE TO CONNECT TO WIFI.",
    "ERROR: GENERAL FAILURE",
    "ERROR: NETWORK NOT FOUND",
    "ERROR: CONNECTION TIMEOUT",
    "SD CARD",
    "\xC2"
    "\xAB"
    " BACK",
    "\xC2"
    "\xAB"
    " EXIT",
    "\xC2"
    "\xAB"
    " HOME",
    "\xC2"
    "\xAB"
    " SAVE",
    "SELECT",
    "TOGGLE",
    "CONFIRM",
    "CANCEL",
    "CONNECT",
    "OPEN",
    "DOWNLOAD",
    "RETRY",
    "YES",
    "NO",
    "ON",
    "OFF",
    "SET",
    "NOT SET",
    "LEFT",
    "RIGHT",
    "UP",
    "DOWN",
    "CAPS",
    "CAPS",
    "OK",
    "[ON]",
    "SLEEP SCREEN COVER FILTER",
    "CONTRAST",
    "FULL W/ PERCENTAGE",
    "FULL W/ BOOK BAR",
    "BOOK BAR ONLY",
    "FULL W/ CHAPTER BAR",
    "UI THEME",
    "CLASSIC",
    "LYRA",
    "SUNLIGHT FADING FIX",
    "REMAP FRONT BUTTONS",
    "OPDS BROWSER",
    "COVER + CUSTOM",
    "RECENTS",
    "RECENT BOOKS",
    "NO RECENT BOOKS",
    "USE CALIBRE WIRELESS DEVICE TRANSFERS",
    "FORGET NETWORK AND REMOVE SAVED PASSWORD?",
    "FORGET NETWORK",
    "STARTING CALIBRE...",
    "SETUP",
    "STATUS",
    "CLEAR",
    "DEFAULT",
    "PRESS A FRONT BUTTON FOR EACH ROLE",
    "UNASSIGNED",
    "ALREADY ASSIGNED",
    "SIDE BUTTON UP: RESET TO DEFAULT LAYOUT",
    "SIDE BUTTON DOWN: CANCEL REMAPPING",
    "BACK (1ST BUTTON)",
    "CONFIRM (2ND BUTTON)",
    "LEFT (3RD BUTTON)",
    "RIGHT (4TH BUTTON)",
    "GO TO %",
    "GO HOME",
    "SYNC PROGRESS",
    "DELETE BOOK CACHE",
    "CHAPTER: ",
    " PAGES  |  ",
    "BOOK: ",
    "SHIFT",
    "SHIFT",
    "LOCK",
    "FOR CALIBRE, ADD /OPDS TO YOUR URL",
    "LEFT/RIGHT: 1%  UP/DOWN: 10%",
    "SYNCING TIME...",
    "CALCULATING DOCUMENT HASH...",
    "FAILED TO CALCULATE DOCUMENT HASH",
    "FETCHING REMOTE PROGRESS...",
    "UPLOADING PROGRESS...",
    "NO CREDENTIALS CONFIGURED",
    "SET UP KOREADER ACCOUNT IN SETTINGS",
    "PROGRESS FOUND!",
    "REMOTE",
    "LOCAL",
    "PAGE %d, %.2f%% OVERALL",
    "PAGE %d/%d, %.2f%% OVERALL",
    "  FROM: %s",
    "APPLY REMOTE PROGRESS",
    "UPLOAD LOCAL PROGRESS",
    "NO REMOTE PROGRESS FOUND",
    "UPLOAD CURRENT POSITION?",
    "PROGRESS UPLOADED!",
    "SYNC FAILED",
    "SECTION ",
    "UPLOAD",
    "BOOK'S STYLE",
    "EMBEDDED STYLE",
    "OPDS SERVER URL",
};

const char* const STRINGS_IT[] = {
    "CrossPoint",
    "BOOTING",
    "SLEEPING",
    "Entering Sleep...",
    "Browse Files",
    "File Transfer",
    "Settings",
    "Calibre Library",
    "Continue Reading",
    "No open book",
    "Start reading below",
    "Books",
    "No books found",
    "Select Chapter",
    "No chapters",
    "End of book",
    "Empty chapter",
    "Indexing...",
    "Memory error",
    "Page load error",
    "Empty file",
    "Out of bounds",
    "Loading...",
    "Failed to load XTC",
    "Failed to load TXT",
    "Failed to load EPUB",
    "SD card error",
    "WiFi Networks",
    "No networks found",
    "%zu networks found",
    "Scanning...",
    "Connecting...",
    "Connected!",
    "Connection Failed",
    "Connection timeout",
    "Forget Network?",
    "Save password for next time?",
    "Remove saved password?",
    "Press OK to scan again",
    "Press any button to continue",
    "LEFT/RIGHT: Select | OK: Confirm",
    "How would you like to connect?",
    "Join a Network",
    "Create Hotspot",
    "Connect to an existing WiFi network",
    "Create a WiFi network others can join",
    "Starting Hotspot...",
    "Hotspot Mode",
    "Connect your device to this WiFi network",
    "Open this URL in your browser",
    "or http://",
    "or scan QR code with your phone:",
    "Calibre Wireless",
    "Calibre Web URL",
    "Connect as Wireless Device",
    "* = Encrypted | + = Saved",
    "MAC address:",
    "Checking WiFi...",
    "Enter WiFi Password",
    "Enter Text",
    "to ",
    "Discovering Calibre...",
    "Connecting to ",
    "Connected to ",
    "Waiting for commands...",
    "(Connection failed, retrying)",
    "Calibre disconnected",
    "Waiting for transfer...",
    "If transfer fails, enable\n'Ignore free space' in Calibre's\nSmartDevice plugin settings.",
    "Receiving: ",
    "Received: ",
    "Waiting for more...",
    "Failed to create file",
    "Password required",
    "Transfer interrupted",
    "1) Install CrossPoint Reader plugin",
    "2) Be on the same WiFi network",
    "3) In Calibre: \"Send to device\"",
    "\"Keep this screen open while sending\"",
    "Display",
    "Reader",
    "Controls",
    "System",
    "Sleep Screen",
    "Sleep Screen Cover Mode",
    "Status Bar",
    "Hide Battery %",
    "Extra Paragraph Spacing",
    "Text Anti-Aliasing",
    "Short Power Button Click",
    "Reading Orientation",
    "Front Button Layout",
    "Side Button Layout (reader)",
    "Long-press Chapter Skip",
    "Reader Font Family",
    "External Reader Font",
    "Reader Font",
    "UI Font",
    "UI Font Size",
    "Reader Line Spacing",
    "ASCII Letter Spacing",
    "ASCII Digit Spacing",
    "CJK Spacing",
    "Color Mode",
    "Reader Screen Margin",
    "Reader Paragraph Alignment",
    "Hyphenation",
    "Time to Sleep",
    "Refresh Frequency",
    "Calibre Settings",
    "KOReader Sync",
    "Check for updates",
    "Language",
    "Select Wallpaper",
    "Clear Reading Cache",
    "Calibre",
    "Username",
    "Password",
    "Sync Server URL",
    "Document Matching",
    "Authenticate",
    "KOReader Username",
    "KOReader Password",
    "Filename",
    "Binary",
    "Set credentials first",
    "WiFi connection failed",
    "Authenticating...",
    "Successfully authenticated!",
    "KOReader Auth",
    "KOReader sync is ready to use",
    "Authentication Failed",
    "Done",
    "This will clear all cached book data.",
    "All reading progress will be lost!",
    "Books will need to be re-indexed",
    "when opened again.",
    "Clearing cache...",
    "Cache Cleared",
    "items removed",
    "failed",
    "Failed to clear cache",
    "Check serial output for details",
    "Dark",
    "Light",
    "Custom",
    "Cover",
    "None",
    "Fit",
    "Crop",
    "No Progress",
    "Full",
    "Never",
    "In Reader",
    "Always",
    "Ignore",
    "Sleep",
    "Page Turn",
    "Portrait",
    "Landscape CW",
    "Inverted",
    "Landscape CCW",
    "Bck, Cnfrm, Lft, Rght",
    "Lft, Rght, Bck, Cnfrm",
    "Lft, Bck, Cnfrm, Rght",
    "Prev/Next",
    "Next/Prev",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Small",
    "Medium",
    "Large",
    "X Large",
    "Tight",
    "Normal",
    "Wide",
    "Justify",
    "Left",
    "Center",
    "Right",
    "1 min",
    "5 min",
    "10 min",
    "15 min",
    "30 min",
    "1 page",
    "5 pages",
    "10 pages",
    "15 pages",
    "30 pages",
    "Update",
    "Checking for update...",
    "New update available!",
    "Current Version: ",
    "New Version: ",
    "Updating...",
    "No update available",
    "Update failed",
    "Update complete",
    "Press and hold power button to turn back on",
    "External Font",
    "Built-in (Disabled)",
    "No entries found",
    "Downloading...",
    "Download failed",
    "Error:",
    "Unnamed",
    "No server URL configured",
    "Failed to fetch feed",
    "Failed to parse feed",
    "Network: ",
    "IP Address: ",
    "or scan QR code with your phone to connect to Wifi.",
    "Error: General failure",
    "Error: Network not found",
    "Error: Connection timeout",
    "SD card",
    "\xC2"
    "\xAB"
    " Back",
    "\xC2"
    "\xAB"
    " Exit",
    "\xC2"
    "\xAB"
    " Home",
    "\xC2"
    "\xAB"
    " Save",
    "Select",
    "Toggle",
    "Confirm",
    "Cancel",
    "Connect",
    "Open",
    "Download",
    "Retry",
    "Yes",
    "No",
    "ON",
    "OFF",
    "Set",
    "Not Set",
    "Left",
    "Right",
    "Up",
    "Down",
    "CAPS",
    "caps",
    "OK",
    "[ON]",
    "Sleep Screen Cover Filter",
    "Contrast",
    "Full w/ Percentage",
    "Full w/ Book Bar",
    "Book Bar Only",
    "Full w/ Chapter Bar",
    "UI Theme",
    "Classic",
    "Lyra",
    "Sunlight Fading Fix",
    "Remap Front Buttons",
    "OPDS Browser",
    "Cover + Custom",
    "Recents",
    "Recent Books",
    "No recent books",
    "Use Calibre wireless device transfers",
    "Forget network and remove saved password?",
    "Forget network",
    "Starting Calibre...",
    "Setup",
    "Status",
    "Clear",
    "Default",
    "Press a front button for each role",
    "Unassigned",
    "Already assigned",
    "Side button Up: Reset to default layout",
    "Side button Down: Cancel remapping",
    "Back (1st button)",
    "Confirm (2nd button)",
    "Left (3rd button)",
    "Right (4th button)",
    "Go to %",
    "Go Home",
    "Sync Progress",
    "Delete Book Cache",
    "Chapter: ",
    " pages  |  ",
    "Book: ",
    "shift",
    "SHIFT",
    "LOCK",
    "For Calibre, add /opds to your URL",
    "Left/Right: 1%  Up/Down: 10%",
    "Syncing time...",
    "Calculating document hash...",
    "Failed to calculate document hash",
    "Fetching remote progress...",
    "Uploading progress...",
    "No credentials configured",
    "Set up KOReader account in Settings",
    "Progress found!",
    "Remote:",
    "Local:",
    "Page %d, %.2f%% overall",
    "Page %d/%d, %.2f%% overall",
    "  From: %s",
    "Apply remote progress",
    "Upload local progress",
    "No remote progress found",
    "Upload current position?",
    "Progress uploaded!",
    "Sync failed",
    "Section ",
    "Upload",
    "Book's Style",
    "Embedded Style",
    "OPDS Server URL",
};

const char* const STRINGS_SW[] = {
    "CrossPoint",
    "BOOTING",
    "SLEEPING",
    "Entering Sleep...",
    "Browse Files",
    "File Transfer",
    "Settings",
    "Calibre Library",
    "Continue Reading",
    "No open book",
    "Start reading below",
    "Books",
    "No books found",
    "Select Chapter",
    "No chapters",
    "End of book",
    "Empty chapter",
    "Indexing...",
    "Memory error",
    "Page load error",
    "Empty file",
    "Out of bounds",
    "Loading...",
    "Failed to load XTC",
    "Failed to load TXT",
    "Failed to load EPUB",
    "SD card error",
    "WiFi Networks",
    "No networks found",
    "%zu networks found",
    "Scanning...",
    "Connecting...",
    "Connected!",
    "Connection Failed",
    "Connection timeout",
    "Forget Network?",
    "Save password for next time?",
    "Remove saved password?",
    "Press OK to scan again",
    "Press any button to continue",
    "LEFT/RIGHT: Select | OK: Confirm",
    "How would you like to connect?",
    "Join a Network",
    "Create Hotspot",
    "Connect to an existing WiFi network",
    "Create a WiFi network others can join",
    "Starting Hotspot...",
    "Hotspot Mode",
    "Connect your device to this WiFi network",
    "Open this URL in your browser",
    "or http://",
    "or scan QR code with your phone:",
    "Calibre Wireless",
    "Calibre Web URL",
    "Connect as Wireless Device",
    "* = Encrypted | + = Saved",
    "MAC address:",
    "Checking WiFi...",
    "Enter WiFi Password",
    "Enter Text",
    "to ",
    "Discovering Calibre...",
    "Connecting to ",
    "Connected to ",
    "Waiting for commands...",
    "(Connection failed, retrying)",
    "Calibre disconnected",
    "Waiting for transfer...",
    "If transfer fails, enable\n'Ignore free space' in Calibre's\nSmartDevice plugin settings.",
    "Receiving: ",
    "Received: ",
    "Waiting for more...",
    "Failed to create file",
    "Password required",
    "Transfer interrupted",
    "1) Install CrossPoint Reader plugin",
    "2) Be on the same WiFi network",
    "3) In Calibre: \"Send to device\"",
    "\"Keep this screen open while sending\"",
    "Display",
    "Reader",
    "Controls",
    "System",
    "Sleep Screen",
    "Sleep Screen Cover Mode",
    "Status Bar",
    "Hide Battery %",
    "Extra Paragraph Spacing",
    "Text Anti-Aliasing",
    "Short Power Button Click",
    "Reading Orientation",
    "Front Button Layout",
    "Side Button Layout (reader)",
    "Long-press Chapter Skip",
    "Reader Font Family",
    "External Reader Font",
    "Reader Font",
    "UI Font",
    "UI Font Size",
    "Reader Line Spacing",
    "ASCII Letter Spacing",
    "ASCII Digit Spacing",
    "CJK Spacing",
    "Color Mode",
    "Reader Screen Margin",
    "Reader Paragraph Alignment",
    "Hyphenation",
    "Time to Sleep",
    "Refresh Frequency",
    "Calibre Settings",
    "KOReader Sync",
    "Check for updates",
    "Language",
    "Select Wallpaper",
    "Clear Reading Cache",
    "Calibre",
    "Username",
    "Password",
    "Sync Server URL",
    "Document Matching",
    "Authenticate",
    "KOReader Username",
    "KOReader Password",
    "Filename",
    "Binary",
    "Set credentials first",
    "WiFi connection failed",
    "Authenticating...",
    "Successfully authenticated!",
    "KOReader Auth",
    "KOReader sync is ready to use",
    "Authentication Failed",
    "Done",
    "This will clear all cached book data.",
    "All reading progress will be lost!",
    "Books will need to be re-indexed",
    "when opened again.",
    "Clearing cache...",
    "Cache Cleared",
    "items removed",
    "failed",
    "Failed to clear cache",
    "Check serial output for details",
    "Dark",
    "Light",
    "Custom",
    "Cover",
    "None",
    "Fit",
    "Crop",
    "No Progress",
    "Full",
    "Never",
    "In Reader",
    "Always",
    "Ignore",
    "Sleep",
    "Page Turn",
    "Portrait",
    "Landscape CW",
    "Inverted",
    "Landscape CCW",
    "Bck, Cnfrm, Lft, Rght",
    "Lft, Rght, Bck, Cnfrm",
    "Lft, Bck, Cnfrm, Rght",
    "Prev/Next",
    "Next/Prev",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Small",
    "Medium",
    "Large",
    "X Large",
    "Tight",
    "Normal",
    "Wide",
    "Justify",
    "Left",
    "Center",
    "Right",
    "1 min",
    "5 min",
    "10 min",
    "15 min",
    "30 min",
    "1 page",
    "5 pages",
    "10 pages",
    "15 pages",
    "30 pages",
    "Update",
    "Checking for update...",
    "New update available!",
    "Current Version: ",
    "New Version: ",
    "Updating...",
    "No update available",
    "Update failed",
    "Update complete",
    "Press and hold power button to turn back on",
    "External Font",
    "Built-in (Disabled)",
    "No entries found",
    "Downloading...",
    "Download failed",
    "Error:",
    "Unnamed",
    "No server URL configured",
    "Failed to fetch feed",
    "Failed to parse feed",
    "Network: ",
    "IP Address: ",
    "or scan QR code with your phone to connect to Wifi.",
    "Error: General failure",
    "Error: Network not found",
    "Error: Connection timeout",
    "SD card",
    "\xC2"
    "\xAB"
    " Back",
    "\xC2"
    "\xAB"
    " Exit",
    "\xC2"
    "\xAB"
    " Home",
    "\xC2"
    "\xAB"
    " Save",
    "Select",
    "Toggle",
    "Confirm",
    "Cancel",
    "Connect",
    "Open",
    "Download",
    "Retry",
    "Yes",
    "No",
    "ON",
    "OFF",
    "Set",
    "Not Set",
    "Left",
    "Right",
    "Up",
    "Down",
    "CAPS",
    "caps",
    "OK",
    "[ON]",
    "Sleep Screen Cover Filter",
    "Contrast",
    "Full w/ Percentage",
    "Full w/ Book Bar",
    "Book Bar Only",
    "Full w/ Chapter Bar",
    "UI Theme",
    "Classic",
    "Lyra",
    "Sunlight Fading Fix",
    "Remap Front Buttons",
    "OPDS Browser",
    "Cover + Custom",
    "Recents",
    "Recent Books",
    "No recent books",
    "Use Calibre wireless device transfers",
    "Forget network and remove saved password?",
    "Forget network",
    "Starting Calibre...",
    "Setup",
    "Status",
    "Clear",
    "Default",
    "Press a front button for each role",
    "Unassigned",
    "Already assigned",
    "Side button Up: Reset to default layout",
    "Side button Down: Cancel remapping",
    "Back (1st button)",
    "Confirm (2nd button)",
    "Left (3rd button)",
    "Right (4th button)",
    "Go to %",
    "Go Home",
    "Sync Progress",
    "Delete Book Cache",
    "Chapter: ",
    " pages  |  ",
    "Book: ",
    "shift",
    "SHIFT",
    "LOCK",
    "For Calibre, add /opds to your URL",
    "Left/Right: 1%  Up/Down: 10%",
    "Syncing time...",
    "Calculating document hash...",
    "Failed to calculate document hash",
    "Fetching remote progress...",
    "Uploading progress...",
    "No credentials configured",
    "Set up KOReader account in Settings",
    "Progress found!",
    "Remote:",
    "Local:",
    "Page %d, %.2f%% overall",
    "Page %d/%d, %.2f%% overall",
    "  From: %s",
    "Apply remote progress",
    "Upload local progress",
    "No remote progress found",
    "Upload current position?",
    "Progress uploaded!",
    "Sync failed",
    "Section ",
    "Upload",
    "Book's Style",
    "Embedded Style",
    "OPDS Server URL",
};

const char* const STRINGS_FR[] = {
    "CrossPoint",
    "D\xC3"
    "\x89"
    "MARRAGE EN COURS",
    "VEILLE",
    "Mise en veille\xE2"
    "\x80"
    "\xA6"
    "",
    "Fichiers",
    "Transfert",
    "R\xC3"
    "\xA9"
    "glages",
    "Biblioth\xC3"
    "\xA8"
    "que Calibre",
    "Continuer la lecture",
    "Aucun livre ouvert",
    "Lisez votre premier livre ci-dessous",
    "Livres",
    "Dossier vide",
    "Choix du chapitre",
    "Aucun chapitre",
    "Fin du livre",
    "Chapitre vide",
    "Indexation en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Erreur de m\xC3"
    "\xA9"
    "moire",
    "Erreur de chargement",
    "Fichier vide",
    "D\xC3"
    "\xA9"
    "passement de m\xC3"
    "\xA9"
    "moire",
    "Chargement\xE2"
    "\x80"
    "\xA6"
    "",
    "Erreur de chargement du fichier XTC",
    "Erreur de chargement du fichier TXT",
    "Erreur de chargement du fichier EPUB",
    "Carte m\xC3"
    "\xA9"
    "moire absente",
    "R\xC3"
    "\xA9"
    "seaux WiFi",
    "Aucun r\xC3"
    "\xA9"
    "seau",
    "%zu r\xC3"
    "\xA9"
    "seaux",
    "Recherche de r\xC3"
    "\xA9"
    "seaux en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Connexion en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Connect\xC3"
    "\xA9"
    " !",
    "\xC3"
    "\x89"
    "chec de la connexion",
    "D\xC3"
    "\xA9"
    "lai de connexion d\xC3"
    "\xA9"
    "pass\xC3"
    "\xA9"
    "",
    "Oublier ce r\xC3"
    "\xA9"
    "seau ?",
    "Enregistrer le mot de passe ?",
    "Supprimer le mot de passe enregistr\xC3"
    "\xA9"
    " ?",
    "Appuyez sur OK pour d\xC3"
    "\xA9"
    "tecter \xC3"
    "\xA0"
    " nouveau",
    "Appuyez sur une touche pour continuer",
    "GAUCHE/DROITE: S\xC3"
    "\xA9"
    "lectionner | OK: Valider",
    "Comment voulez-vous vous connecter ?",
    "Connexion \xC3"
    "\xA0"
    " un r\xC3"
    "\xA9"
    "seau",
    "Cr\xC3"
    "\xA9"
    "er un point d\xE2"
    "\x80"
    "\x99"
    "acc\xC3"
    "\xA8"
    "s",
    "Se connecter \xC3"
    "\xA0"
    " un r\xC3"
    "\xA9"
    "seau WiFi existant",
    "Cr\xC3"
    "\xA9"
    "er un r\xC3"
    "\xA9"
    "seau WiFi accessible depuis d\xE2"
    "\x80"
    "\x99"
    "autres appareils",
    "Cr\xC3"
    "\xA9"
    "ation du point d\xE2"
    "\x80"
    "\x99"
    "acc\xC3"
    "\xA8"
    "s en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Mode point d\xE2"
    "\x80"
    "\x99"
    "acc\xC3"
    "\xA8"
    "s",
    "Connectez un appareil \xC3"
    "\xA0"
    " ce r\xC3"
    "\xA9"
    "seau WiFi",
    "Ouvrez cette URL dans votre navigateur",
    "ou http://",
    "ou scannez le QR code avec votre t\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "phone",
    "Connexion \xC3"
    "\xA0"
    " Calibre sans fil",
    "URL Web Calibre",
    "Se connecter comme appareil sans fil",
    "* = S\xC3"
    "\xA9"
    "curis\xC3"
    "\xA9"
    " | + = Sauvegard\xC3"
    "\xA9"
    "",
    "Adresse MAC :",
    "V\xC3"
    "\xA9"
    "rification du r\xC3"
    "\xA9"
    "seau WiFi...",
    "Entrez le mot de passe WiFi",
    "Entrez le texte",
    "\xC3"
    "\xA0"
    " ",
    "Recherche de Calibre en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Connexion \xC3"
    "\xA0"
    " ",
    "Connect\xC3"
    "\xA9"
    " \xC3"
    "\xA0"
    "  ",
    "En attente de commandes\xE2"
    "\x80"
    "\xA6"
    "",
    "(\xC3"
    "\x89"
    "chec de la connexion, nouvelle tentative)",
    "Calibre d\xC3"
    "\xA9"
    "connect\xC3"
    "\xA9"
    "",
    "En attente de transfert\xE2"
    "\x80"
    "\xA6"
    "",
    "Si le transfert \xC3"
    "\xA9"
    "choue, activez\n\xE2"
    "\x80"
    "\x99"
    "Ignorer l\xE2"
    "\x80"
    "\x99"
    "espace libre\xE2"
    "\x80"
    "\x99"
    " dans les\nparam\xC3"
    "\xA8"
    "tres du plugin SmartDevice de Calibre.",
    "R\xC3"
    "\xA9"
    "ception : ",
    "Re\xC3"
    "\xA7"
    "us : ",
    "En attente de donn\xC3"
    "\xA9"
    "es suppl\xC3"
    "\xA9"
    "mentaires\xE2"
    "\x80"
    "\xA6"
    "",
    "\xC3"
    "\x89"
    "chec de la cr\xC3"
    "\xA9"
    "ation du fichier",
    "Mot de passe requis",
    "Transfert interrompu",
    "1) Installer le plugin CrossPoint Reader",
    "2) Se connecter au m\xC3"
    "\xAA"
    "me r\xC3"
    "\xA9"
    "seau WiFi",
    "3) Dans Calibre : \xE2"
    "\x80"
    "\x98"
    "Envoyer vers l\xE2"
    "\x80"
    "\x99"
    "appareil\xE2"
    "\x80"
    "\x99"
    "",
    "\xE2"
    "\x80"
    "\x9C"
    "Gardez cet \xC3"
    "\xA9"
    "cran ouvert pendant le transfert\xE2"
    "\x80"
    "\x9D"
    "",
    "Affichage",
    "Lecteur",
    "Commandes",
    "Syst\xC3"
    "\xA8"
    "me",
    "\xC3"
    "\x89"
    "cran de veille",
    "Mode d\xE2"
    "\x80"
    "\x99"
    "image de l\xE2"
    "\x80"
    "\x99"
    "\xC3"
    "\xA9"
    "cran de veille",
    "Barre d\xE2"
    "\x80"
    "\x99"
    "\xC3"
    "\xA9"
    "tat",
    "Masquer % batterie",
    "Espacement des paragraphes",
    "Lissage du texte",
    "Appui court bout. alim.",
    "Orientation de lecture",
    "Disposition des boutons avant",
    "Disposition des boutons lat\xC3"
    "\xA9"
    "raux",
    "Appui long pour saut de chapitre",
    "Police de caract\xC3"
    "\xA8"
    "res du lecteur",
    "Police externe",
    "Police du lecteur",
    "Police de l\xE2"
    "\x80"
    "\x99"
    "interface",
    "Taille du texte de l\xE2"
    "\x80"
    "\x99"
    "interface",
    "Espacement des lignes",
    "Espacement des lettres ASCII",
    "Espacement des chiffres ASCII",
    "Espacement CJK",
    "Mode couleur",
    "Marges du lecteur",
    "Alignement des paragraphes",
    "C\xC3"
    "\xA9"
    "sure",
    "Mise en veille automatique",
    "Fr\xC3"
    "\xA9"
    "quence de rafra\xC3"
    "\xAE"
    "chissement",
    "R\xC3"
    "\xA9"
    "glages Calibre",
    "Synchronisation KOReader",
    "Mise \xC3"
    "\xA0"
    " jour",
    "Langue",
    "Fond d\xE2"
    "\x80"
    "\x99"
    "\xC3"
    "\xA9"
    "cran",
    "Vider le cache de lecture",
    "Calibre",
    "Nom d\xE2"
    "\x80"
    "\x99"
    "utilisateur",
    "Mot de passe",
    "URL du serveur",
    "Correspondance",
    "Se connecter",
    "Nom d\xE2"
    "\x80"
    "\x99"
    "utilisateur",
    "Mot de passe",
    "Nom de fichier",
    "Binaire",
    "Identifiants manquants",
    "\xC3"
    "\x89"
    "chec de connexion WiFi",
    "Connexion en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Connexion r\xC3"
    "\xA9"
    "ussie !",
    "Auth KOReader",
    "Synchronisation KOReader pr\xC3"
    "\xAA"
    "te",
    "\xC3"
    "\x89"
    "chec de la connexion",
    "OK",
    "Le cache de votre biblioth\xC3"
    "\xA8"
    "que sera enti\xC3"
    "\xA8"
    "rement vid\xC3"
    "\xA9"
    "",
    "Votre progression de lecture sera perdue !",
    "Les livres devront \xC3"
    "\xAA"
    "tre r\xC3"
    "\xA9"
    "index\xC3"
    "\xA9"
    "s",
    "\xC3"
    "\xA0"
    " leur prochaine ouverture.",
    "Suppression du cache\xE2"
    "\x80"
    "\xA6"
    "",
    "Cache supprim\xC3"
    "\xA9"
    "",
    "\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "ments supprim\xC3"
    "\xA9"
    "s",
    "ont \xC3"
    "\xA9"
    "chou\xC3"
    "\xA9"
    "",
    "\xC3"
    "\x89"
    "chec de la suppression du cache",
    "V\xC3"
    "\xA9"
    "rifiez la console s\xC3"
    "\xA9"
    "rie pour plus de d\xC3"
    "\xA9"
    "tails",
    "Sombre",
    "Clair",
    "Custom",
    "Couverture",
    "Aucun",
    "Ajust\xC3"
    "\xA9"
    "",
    "Rogn\xC3"
    "\xA9"
    "",
    "Sans progression",
    "Compl\xC3"
    "\xA8"
    "te",
    "Jamais",
    "Dans le lecteur",
    "Toujours",
    "Ignorer",
    "Mise en veille",
    "Page suivante",
    "Portrait",
    "Paysage",
    "Invers\xC3"
    "\xA9"
    "",
    "Paysage invers\xC3"
    "\xA9"
    "",
    "Ret, OK, Gauche, Droite",
    "Gauche, Droite, Ret, OK",
    "Gauche, Ret, OK, Droite",
    "Prec/Suiv",
    "Suiv/Prec",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Petite",
    "Moyenne",
    "Grande",
    "T Grande",
    "Serr\xC3"
    "\xA9"
    "",
    "Normal",
    "Large",
    "Justifier",
    "Gauche",
    "Centre",
    "Droite",
    "1 min",
    "5 min",
    "10 min",
    "15 min",
    "30 min",
    "1 page",
    "5 pages",
    "10 pages",
    "15 pages",
    "30 pages",
    "Mise \xC3"
    "\xA0"
    " jour",
    "Recherche de mises \xC3"
    "\xA0"
    " jour en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Nouvelle mise \xC3"
    "\xA0"
    " jour disponible !",
    "Version actuelle :",
    "Nouvelle version : ",
    "Mise \xC3"
    "\xA0"
    " jour en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "Aucune mise \xC3"
    "\xA0"
    " jour disponible",
    "\xC3"
    "\x89"
    "chec de la mise \xC3"
    "\xA0"
    " jour",
    "Mise \xC3"
    "\xA0"
    " jour effectu\xC3"
    "\xA9"
    "e",
    "Maintenir le bouton d\xE2"
    "\x80"
    "\x99"
    "alimentation pour red\xC3"
    "\xA9"
    "marrer",
    "Police externe",
    "Int\xC3"
    "\xA9"
    "gr\xC3"
    "\xA9"
    "e (d\xC3"
    "\xA9"
    "sactiv\xC3"
    "\xA9"
    "e)",
    "Aucune entr\xC3"
    "\xA9"
    "e trouv\xC3"
    "\xA9"
    "e",
    "T\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "chargement en cours\xE2"
    "\x80"
    "\xA6"
    "",
    "\xC3"
    "\x89"
    "chec du t\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "chargement",
    "Erreur : ",
    "Sans titre",
    "Aucune URL serveur configur\xC3"
    "\xA9"
    "e",
    "\xC3"
    "\x89"
    "chec du t\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "chargement du flux",
    "\xC3"
    "\x89"
    "chec de l\xE2"
    "\x80"
    "\x99"
    "analyse du flux",
    "R\xC3"
    "\xA9"
    "seau : ",
    "Adresse IP : ",
    "or scan QR code with your phone to connect to Wifi.",
    "Erreur : \xC3"
    "\x89"
    "chec g\xC3"
    "\xA9"
    "n\xC3"
    "\xA9"
    "ral",
    "Erreur : R\xC3"
    "\xA9"
    "seau introuvable",
    "Erreur : D\xC3"
    "\xA9"
    "lai de connexion d\xC3"
    "\xA9"
    "pass\xC3"
    "\xA9"
    "",
    "Carte SD",
    "\xC2"
    "\xAB"
    " Retour",
    "\xC2"
    "\xAB"
    " Sortie",
    "\xC2"
    "\xAB"
    " Accueil",
    "\xC2"
    "\xAB"
    " Sauver",
    "OK",
    "Modifier",
    "Confirmer",
    "Annuler",
    "OK",
    "Ouvrir",
    "T\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "charger",
    "R\xC3"
    "\xA9"
    "essayer",
    "Oui",
    "Non",
    "ON",
    "OFF",
    "D\xC3"
    "\xA9"
    "fini",
    "Non d\xC3"
    "\xA9"
    "fini",
    "Gauche",
    "Droite",
    "Haut",
    "Bas",
    "MAJ",
    "maj",
    "OK",
    "[ON]",
    "Filtre affichage veille",
    "Contraste",
    "Compl\xC3"
    "\xA8"
    "te + %",
    "Compl\xC3"
    "\xA8"
    "te + barre livre",
    "Barre livre",
    "Compl\xC3"
    "\xA8"
    "te + barre chapitre",
    "Th\xC3"
    "\xA8"
    "me de l\xE2"
    "\x80"
    "\x99"
    "interface",
    "Classique",
    "Lyra",
    "Am\xC3"
    "\xA9"
    "lioration de la lisibilit\xC3"
    "\xA9"
    " au soleil",
    "R\xC3"
    "\xA9"
    "assigner les boutons avant",
    "Navigateur OPDS",
    "Couverture + Custom",
    "R\xC3"
    "\xA9"
    "cents",
    "Livres r\xC3"
    "\xA9"
    "cents",
    "Aucun livre r\xC3"
    "\xA9"
    "cent",
    "Utiliser les transferts sans fil Calibre",
    "Oublier le r\xC3"
    "\xA9"
    "seau et supprimer le mot de passe enregistr\xC3"
    "\xA9"
    " ?",
    "Oublier le r\xC3"
    "\xA9"
    "seau",
    "D\xC3"
    "\xA9"
    "marrage de Calibre...",
    "Configuration",
    "Statut",
    "Effacer",
    "D\xC3"
    "\xA9"
    "faut",
    "Appuyez sur un bouton avant pour chaque r\xC3"
    "\xB4"
    "le",
    "Non assign\xC3"
    "\xA9"
    "",
    "D\xC3"
    "\xA9"
    "j\xC3"
    "\xA0"
    " assign\xC3"
    "\xA9"
    "",
    "Bouton lat\xC3"
    "\xA9"
    "ral haut : R\xC3"
    "\xA9"
    "initialiser",
    "Bouton lat\xC3"
    "\xA9"
    "ral bas : Annuler le r\xC3"
    "\xA9"
    "glage",
    "Retour (1er bouton)",
    "OK (2\xC3"
    "\xA8"
    "me bouton)",
    "Gauche (3\xC3"
    "\xA8"
    "me bouton)",
    "Droite (4\xC3"
    "\xA8"
    "me bouton)",
    "Aller \xC3"
    "\xA0"
    " %",
    "Aller \xC3"
    "\xA0"
    " l\xE2"
    "\x80"
    "\x99"
    "accueil",
    "Synchroniser la progression",
    "Supprimer le cache du livre",
    "Chapitre : ",
    " pages  |  ",
    "Livre : ",
    "maj",
    "MAJ",
    "VERR MAJ",
    "Pour Calibre, ajoutez /opds \xC3"
    "\xA0"
    " l\xE2"
    "\x80"
    "\x99"
    "URL",
    "Gauche/Droite : 1%  Haut/Bas : 10%",
    "Synchronisation de l\xE2"
    "\x80"
    "\x99"
    "heure\xE2"
    "\x80"
    "\xA6"
    "",
    "Calcul du hash du document\xE2"
    "\x80"
    "\xA6"
    "",
    "\xC3"
    "\x89"
    "chec du calcul du hash du document",
    "T\xC3"
    "\xA9"
    "l\xC3"
    "\xA9"
    "chargement de la progression\xE2"
    "\x80"
    "\xA6"
    "",
    "Envoi de la progression\xE2"
    "\x80"
    "\xA6"
    "",
    "Aucun identifiant configur\xC3"
    "\xA9"
    "",
    "Configurez le compte KOReader dans les r\xC3"
    "\xA9"
    "glages",
    "Progression trouv\xC3"
    "\xA9"
    "e !",
    "En ligne :",
    "Locale :",
    "Page %d, %.2f%% au total",
    "Page %d/%d, %.2f%% au total",
    "  De : %s",
    "Appliquer la progression en ligne",
    "Envoyer la progression locale",
    "Aucune progression en ligne trouv\xC3"
    "\xA9"
    "e",
    "Envoyer la position actuelle ?",
    "Progression envoy\xC3"
    "\xA9"
    "e !",
    "\xC3"
    "\x89"
    "chec de la synchronisation",
    "Section ",
    "Envoi",
    "Style du livre",
    "Style int\xC3"
    "\xA9"
    "gr\xC3"
    "\xA9"
    "",
    "URL du serveur OPDS",
};

const char* const STRINGS_DE[] = {
    "CrossPoint",
    "STARTEN",
    "STANDBY",
    "Standby...",
    "Durchsuchen",
    "Datentransfer",
    "Einstellungen",
    "Calibre-Bibliothek",
    "Weiterlesen",
    "Aktuell kein Buch",
    "Lesen beginnen",
    "B\xC3"
    "\xBC"
    "cher",
    "Keine B\xC3"
    "\xBC"
    "cher",
    "Kapitel ausw\xC3"
    "\xA4"
    "hlen",
    "Keine Kapitel",
    "Buchende",
    "Kapitelende",
    "Indexieren\xE2"
    "\x80"
    "\xA6"
    "",
    "Speicherfehler",
    "Seitenladefehler",
    "Leere Datei",
    "Zu gro\xC3"
    "\x9F"
    "",
    "Laden\xE2"
    "\x80"
    "\xA6"
    "",
    "Ladefehler bei XTC",
    "Ladefehler bei TXT",
    "Ladefehler bei EPUB",
    "SD-Karten-Fehler",
    "WLAN-Netzwerke",
    "Kein WLAN gefunden",
    "%zu WLAN-Netzwerke gefunden",
    "Suchen...",
    "Verbinden...",
    "Verbunden!",
    "Verbindungsfehler",
    "Verbindungs-Timeout",
    "WLAN vergessen?",
    "Passwort speichern?",
    "Passwort entfernen?",
    "OK f\xC3"
    "\xBC"
    "r neue Suche",
    "Beliebige Taste dr\xC3"
    "\xBC"
    "cken",
    "links/rechts: Auswahl | OK: Best",
    "Wie m\xC3"
    "\xB6"
    "chtest du dich verbinden?",
    "Netzwerk beitreten",
    "Hotspot erstellen",
    "Mit einem bestehenden WLAN verbinden",
    "WLAN f\xC3"
    "\xBC"
    "r andere erstellen",
    "Hotspot starten\xE2"
    "\x80"
    "\xA6"
    "",
    "Hotspot-Modus",
    "Ger\xC3"
    "\xA4"
    "t mit diesem WLAN verbinden",
    "Diese URL im Browser \xC3"
    "\xB6"
    "ffnen",
    "oder http://",
    "oder QR-Code mit dem Handy scannen:",
    "Calibre Wireless",
    "Calibre-Web-URL",
    "Als Drahtlos-Ger\xC3"
    "\xA4"
    "t hinzuf\xC3"
    "\xBC"
    "gen",
    "* = Verschl\xC3"
    "\xBC"
    "sselt | + = Gespeichert",
    "MAC-Adresse:",
    "WLAN pr\xC3"
    "\xBC"
    "fen\xE2"
    "\x80"
    "\xA6"
    "",
    "WLAN-Passwort eingeben",
    "Text eingeben",
    "bis",
    "Calibre finden...",
    "Verbinden mit",
    "Verbunden mit",
    "Auf Befehle warten\xE2"
    "\x80"
    "\xA6"
    "",
    "(Keine Verbindung, wiederholen)",
    "Calibre getrennt",
    "Auf \xC3"
    "\x9C"
    "bertragung warten...",
    "Bei \xC3"
    "\x9C"
    "bertragungsfehler \n'Freien Speicher ign.' in den\nCalibre-Einstellungen einschalten.",
    "Empfange:",
    "Empfangen:",
    "Auf mehr warten\xE2"
    "\x80"
    "\xA6"
    "",
    "Speicherfehler",
    "Passwort n\xC3"
    "\xB6"
    "tig",
    "\xC3"
    "\x9C"
    "bertragung unterbrochen",
    "1) CrossPoint Reader-Plugin installieren",
    "2) Mit selbem WLAN verbinden",
    "3) In Calibre: \"An Ger\xC3"
    "\xA4"
    "t senden\"",
    "Bildschirm beim Senden offenlassen",
    "Anzeige",
    "Lesen",
    "Bedienung",
    "System",
    "Standby-Bild",
    "Standby-Bildmodus",
    "Statusleiste",
    "Batterie % ausblenden",
    "Absatzabstand",
    "Schriftgl\xC3"
    "\xA4"
    "ttung",
    "An-Taste kurz dr\xC3"
    "\xBC"
    "cken",
    "Leseausrichtung",
    "Vorderes Tastenlayout",
    "Seitliche Tasten (Lesen)",
    "Langes Dr\xC3"
    "\xBC"
    "cken springt Kap.",
    "Lese-Schriftfamilie",
    "Externe Schriftart",
    "Lese-Schriftart",
    "Men\xC3"
    "\xBC"
    "-Schriftart",
    "Schriftgr\xC3"
    "\xB6"
    "\xC3"
    "\x9F"
    "e",
    "Lese-Zeilenabstand",
    "ASCII-Zeichenabstand",
    "ASCII-Ziffernabstand",
    "CJK-Zeichenabstand",
    "Farbmodus",
    "Lese-Seitenr\xC3"
    "\xA4"
    "nder",
    "Lese-Absatzausrichtung",
    "Silbentrennung",
    "Standby nach",
    "Anti-Ghosting nach",
    "Calibre-Einstellungen",
    "KOReader-Synchr.",
    "Nach Updates suchen",
    "Sprache",
    "Bildauswahl Standby",
    "Lese-Cache leeren",
    "Calibre",
    "Benutzername",
    "Passwort n\xC3"
    "\xB6"
    "tig",
    "Sync-Server-URL",
    "Dateizuordnung",
    "Authentifizieren",
    "KOReader-Benutzername",
    "KOReader-Passwort",
    "Dateiname",
    "Bin\xC3"
    "\xA4"
    "rdatei",
    "Zuerst anmelden",
    "WLAN-Verbindung fehlgeschlagen",
    "Authentifizieren\xE2"
    "\x80"
    "\xA6"
    "",
    "Erfolgreich authentifiziert!",
    "KOReader-Auth",
    "KOReader-Synchronisierung bereit",
    "Authentifizierung fehlg.",
    "Erledigt",
    "Alle Buch-Caches werden geleert.",
    "Lesefortschritt wird gel\xC3"
    "\xB6"
    "scht!",
    "B\xC3"
    "\xBC"
    "cher m\xC3"
    "\xBC"
    "ssen beim \xC3"
    "\x96"
    "ffnen",
    "neu eingelesen werden.",
    "Cache leeren\xE2"
    "\x80"
    "\xA6"
    "",
    "Cache geleert",
    "Eintr\xC3"
    "\xA4"
    "ge entfernt",
    "fehlgeschlagen",
    "Fehler beim Cache-Leeren",
    "Serielle Ausgabe pr\xC3"
    "\xBC"
    "fen",
    "Dunkel",
    "Hell",
    "Eigenes",
    "Umschlag",
    "Leer",
    "Anpassen",
    "Zuschnitt",
    "Ohne Fortschr.",
    "Vollst.",
    "Nie",
    "Beim Lesen",
    "Immer",
    "Ignorieren",
    "Standby",
    "Umbl\xC3"
    "\xA4"
    "ttern",
    "Hochformat",
    "Querformat rechts",
    "Invertiert",
    "Querformat links",
    "Zur\xC3"
    "\xBC"
    "ck, Bst, L, R",
    "L, R, Zur\xC3"
    "\xBC"
    "ck, Bst",
    "L, Zur\xC3"
    "\xBC"
    "ck, Bst, R",
    "Zur\xC3"
    "\xBC"
    "ck/Weiter",
    "Weiter/Zu\xC3"
    "\xBC"
    "rck",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Klein",
    "Mittel",
    "Gro\xC3"
    "\x9F"
    "",
    "Extragro\xC3"
    "\x9F"
    "",
    "Eng",
    "Normal",
    "Breit",
    "Blocksatz",
    "Links",
    "Zentriert",
    "Rechts",
    "1 Min",
    "5 Min",
    "10 Min",
    "15 Min",
    "30 Min",
    "1 Seite",
    "5 Seiten",
    "10 Seiten",
    "15 Seiten",
    "30 Seiten",
    "Update",
    "Update suchen\xE2"
    "\x80"
    "\xA6"
    "",
    "Neues Update verf\xC3"
    "\xBC"
    "gbar!",
    "Aktuelle Version:",
    "Neue Version:",
    "Aktualisiere\xE2"
    "\x80"
    "\xA6"
    "",
    "Kein Update verf\xC3"
    "\xBC"
    "gbar",
    "Updatefehler",
    "Update fertig",
    "An-Knopf lang dr\xC3"
    "\xBC"
    "cken, um neuzustarten",
    "Externe Schrift",
    "Vorinstalliert (aus)",
    "Keine Eintr\xC3"
    "\xA4"
    "ge",
    "Herunterladen\xE2"
    "\x80"
    "\xA6"
    "",
    "Ladefehler",
    "Fehler:",
    "Unbenannt",
    "Keine Server-URL konfiguriert",
    "Feedfehler",
    "Feed-Format ung\xC3"
    "\xBC"
    "ltig",
    "Netzwerk:",
    "IP-Adresse:",
    "oder QR-Code mit dem Handy scannen f\xC3"
    "\xBC"
    "r WLAN.",
    "Fehler: Allgemeiner Fehler",
    "Fehler: Kein Netzwerk",
    "Fehler: Zeit\xC3"
    "\xBC"
    "berschreitung",
    "SD-Karte",
    "\xC2"
    "\xAB"
    " Zur\xC3"
    "\xBC"
    "ck",
    "\xC2"
    "\xAB"
    " Verlassen",
    "\xC2"
    "\xAB"
    " Start",
    "\xC2"
    "\xAB"
    " Speichern",
    "Auswahl",
    "\xC3"
    "\x84"
    "ndern",
    "Best\xC3"
    "\xA4"
    "tigen",
    "Abbrechen",
    "Verbinden",
    "\xC3"
    "\x96"
    "ffnen",
    "Herunterladen",
    "Wiederh.",
    "Ja",
    "Nein",
    "An",
    "Aus",
    "Gesetzt",
    "Leer",
    "Links",
    "Rechts",
    "Hoch",
    "Runter",
    "UMSCH",
    "umsch",
    "OK",
    "[AN]",
    "Standby-Coverfilter",
    "Kontrast",
    "Komplett + Prozent",
    "Komplett + Buch",
    "Nur Buch",
    "Komplett + Kapitel",
    "System-Design",
    "Klassisch",
    "Lyra",
    "Anti-Verblassen",
    "Vordere Tasten belegen",
    "OPDS-Browser",
    "Umschlag + Eigenes",
    "Zuletzt",
    "Zuletzt gelesen",
    "Keine B\xC3"
    "\xBC"
    "cher",
    "Calibre-\xC3"
    "\x9C"
    "bertragung (WLAN)",
    "WLAN entfernen & Passwort l\xC3"
    "\xB6"
    "schen?",
    "WLAN entfernen",
    "Calibre starten\xE2"
    "\x80"
    "\xA6"
    "",
    "Installation",
    "Status",
    "Leeren",
    "Standard",
    "Entsprechende Vordertaste dr\xC3"
    "\xBC"
    "cken",
    "Leer",
    "Bereits zugeordnet",
    "Seitentaste hoch: Standard",
    "Seitentaste runter: Abbrechen",
    "Zur\xC3"
    "\xBC"
    "ck (1. Taste)",
    "Best\xC3"
    "\xA4"
    "tigen (2. Taste)",
    "Links (3. Taste)",
    "Rechts (4. Taste)",
    "Gehe zu %",
    "Zum Anfang",
    "Fortschritt synchronisieren",
    "Buch-Cache leeren",
    "Kapitel:",
    " Seiten  |  ",
    "Buch: ",
    "umsch",
    "UMSCH",
    "FESTST",
    "Calibre: URL um /opds erg\xC3"
    "\xA4"
    "nzen",
    "links/rechts: 1% hoch/runter: 10%",
    "Zeit synchonisieren\xE2"
    "\x80"
    "\xA6"
    "",
    "Dokument-Hash berechnen\xE2"
    "\x80"
    "\xA6"
    "",
    "Dokument-Hash fehlgeschlagen",
    "Externen Fortschritt abrufen...",
    "Fortschritt hochladen\xE2"
    "\x80"
    "\xA6"
    "",
    "Zugangsdaten fehlen",
    "KOReader-Konto unter Einst. anlegen",
    "Gefunden!",
    "Extern:",
    "Lokal:",
    "  Seite %d, %.2f%% insgesamt",
    "  Seite %d/%d, %.2f%% insgesamt",
    "  Von: %s",
    "Ext. Fortschritt \xC3"
    "\xBC"
    "bern.",
    "Lokalen Fortschritt hochl.",
    "Kein externer Fortschritt",
    "Aktuelle Position hochladen?",
    "Hochgeladen!",
    "Fehlgeschlagen",
    "Abschnitt",
    "Hochladen",
    "Buch-Stil",
    "Eingebetteter Stil",
    "OPDS-Server-URL",
};

const char* const STRINGS_CZ[] = {
    "CrossPoint",
    "SPU\xC5"
    "\xA0"
    "T\xC4"
    "\x9A"
    "N\xC3"
    "\x8D"
    "",
    "SP\xC3"
    "\x81"
    "NEK",
    "Vstup do re\xC5"
    "\xBE"
    "imu sp\xC3"
    "\xA1"
    "nku...",
    "Proch\xC3"
    "\xA1"
    "zet soubory",
    "P\xC5"
    "\x99"
    "enos soubor\xC5"
    "\xAF"
    "",
    "Nastaven\xC3"
    "\xAD"
    "",
    "Knihovna Calibre",
    "Pokra\xC4"
    "\x8D"
    "ovat ve \xC4"
    "\x8D"
    "ten\xC3"
    "\xAD"
    "",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA1"
    " otev\xC5"
    "\x99"
    "en\xC3"
    "\xA1"
    " kniha",
    "Za\xC4"
    "\x8D"
    "n\xC4"
    "\x9B"
    "te \xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "st n\xC3"
    "\xAD"
    "\xC5"
    "\xBE"
    "e",
    "Knihy",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA9"
    " knihy nenalezeny",
    "Vybrat kapitolu",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA9"
    " kapitoly",
    "Konec knihy",
    "Pr\xC3"
    "\xA1"
    "zdn\xC3"
    "\xA1"
    " kapitola",
    "Indexov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "Chyba pam\xC4"
    "\x9B"
    "ti",
    "Chyba na\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "t\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " str\xC3"
    "\xA1"
    "nky",
    "Pr\xC3"
    "\xA1"
    "zdn\xC3"
    "\xBD"
    " soubor",
    "Mimo hranice",
    "Na\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "t\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "Nepoda\xC5"
    "\x99"
    "ilo se na\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "st XTC",
    "Nepoda\xC5"
    "\x99"
    "ilo se na\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "st TXT",
    "Nepoda\xC5"
    "\x99"
    "ilo se na\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "st EPUB",
    "Chyba SD karty",
    "Wi-Fi s\xC3"
    "\xAD"
    "t\xC4"
    "\x9B"
    "",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA9"
    " s\xC3"
    "\xAD"
    "t\xC4"
    "\x9B"
    " nenalezeny",
    "Nalezeno %zu s\xC3"
    "\xAD"
    "t\xC3"
    "\xAD"
    "",
    "Skenov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "P\xC5"
    "\x99"
    "ipojov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "P\xC5"
    "\x99"
    "ipojeno!",
    "P\xC5"
    "\x99"
    "ipojen\xC3"
    "\xAD"
    " se nezda\xC5"
    "\x99"
    "ilo",
    "\xC4"
    "\x8C"
    "asov\xC3"
    "\xBD"
    " limit p\xC5"
    "\x99"
    "ipojen\xC3"
    "\xAD"
    "",
    "Zapomenout s\xC3"
    "\xAD"
    "\xC5"
    "\xA5"
    "?",
    "Ulo\xC5"
    "\xBE"
    "it heslo pro p\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "\xC5"
    "\xA1"
    "t\xC4"
    "\x9B"
    "?",
    "Odstranit ulo\xC5"
    "\xBE"
    "en\xC3"
    "\xA9"
    " heslo?",
    "Stiskn\xC4"
    "\x9B"
    "te OK pro p\xC5"
    "\x99"
    "eskenov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "",
    "Pokra\xC4"
    "\x8D"
    "ujte stiskem libovoln\xC3"
    "\xA9"
    " kl\xC3"
    "\xA1"
    "vesy",
    "VLEVO/VPRAVO: Vybrat | OK: Potvrdit",
    "Jak se chcete p\xC5"
    "\x99"
    "ipojit?",
    "P\xC5"
    "\x99"
    "ipojit se k s\xC3"
    "\xAD"
    "ti",
    "Vytvo\xC5"
    "\x99"
    "it hotspot",
    "P\xC5"
    "\x99"
    "ipojit se k existuj\xC3"
    "\xAD"
    "c\xC3"
    "\xAD"
    " s\xC3"
    "\xAD"
    "ti WiFi",
    "Vytvo\xC5"
    "\x99"
    "it s\xC3"
    "\xAD"
    "\xC5"
    "\xA5"
    " WiFi, ke kter\xC3"
    "\xA9"
    " se mohou p\xC5"
    "\x99"
    "ipojit ostatn\xC3"
    "\xAD"
    "",
    "Spou\xC5"
    "\xA1"
    "t\xC4"
    "\x9B"
    "n\xC3"
    "\xAD"
    " hotspotu...",
    "Re\xC5"
    "\xBE"
    "im hotspotu",
    "P\xC5"
    "\x99"
    "ipojte sv\xC3"
    "\xA9"
    " za\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "zen\xC3"
    "\xAD"
    " k t\xC3"
    "\xA9"
    "to s\xC3"
    "\xAD"
    "ti WiFi",
    "Otev\xC5"
    "\x99"
    "ete tuto URL ve sv\xC3"
    "\xA9"
    "m prohl\xC3"
    "\xAD"
    "\xC5"
    "\xBE"
    "e\xC4"
    "\x8D"
    "i",
    "nebo http://",
    "nebo naskenujte QR k\xC3"
    "\xB3"
    "d telefonem:",
    "Calibre Wireless",
    "URL webu Calibre",
    "P\xC5"
    "\x99"
    "ipojit jako bezdr\xC3"
    "\xA1"
    "tov\xC3"
    "\xA9"
    " za\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "zen\xC3"
    "\xAD"
    "",
    "* = \xC5"
    "\xA0"
    "ifrov\xC3"
    "\xA1"
    "no | + = Ulo\xC5"
    "\xBE"
    "eno",
    "MAC adresa:",
    "Kontrola WiFi...",
    "Zadejte heslo WiFi",
    "Zadejte text",
    "pro",
    "Prozkoum\xC3"
    "\xA1"
    "v\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " Calibre...",
    "P\xC5"
    "\x99"
    "ipojov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " k",
    "P\xC5"
    "\x99"
    "ipojeno k",
    "\xC4"
    "\x8C"
    "ek\xC3"
    "\xA1"
    "m na p\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "kazy\xE2"
    "\x80"
    "\xA6"
    "",
    "(P\xC5"
    "\x99"
    "ipojen\xC3"
    "\xAD"
    " se nezda\xC5"
    "\x99"
    "ilo, opakov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " pokusu)",
    "Calibre odpojeno",
    "\xC4"
    "\x8C"
    "ek\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " na p\xC5"
    "\x99"
    "enos...",
    "Nezda\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "-li se p\xC5"
    "\x99"
    "enos, povolte\n\xE2"
    "\x80"
    "\x9E"
    "Ignorovat voln\xC3"
    "\xA9"
    " m\xC3"
    "\xAD"
    "sto\xE2"
    "\x80"
    "\x9C"
    " v Calibre\nnastaven\xC3"
    "\xAD"
    " pluginu SmartDevice.",
    "P\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "jem:",
    "P\xC5"
    "\x99"
    "ijato:",
    "\xC4"
    "\x8C"
    "ek\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " na dal\xC5"
    "\xA1"
    "\xC3"
    "\xAD"
    "...",
    "Nepoda\xC5"
    "\x99"
    "ilo se vytvo\xC5"
    "\x99"
    "it soubor",
    "Vy\xC5"
    "\xBE"
    "adov\xC3"
    "\xA1"
    "no heslo",
    "P\xC5"
    "\x99"
    "enos p\xC5"
    "\x99"
    "eru\xC5"
    "\xA1"
    "en",
    "1) Nainstalujte plugin CrossPoint Reader",
    "2) Bu\xC4"
    "\x8F"
    "te ve stejn\xC3"
    "\xA9"
    " s\xC3"
    "\xAD"
    "ti WiFi",
    "3) V Calibre: \xE2"
    "\x80"
    "\x9E"
    "Odeslat do za\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "zen\xC3"
    "\xAD"
    "\xE2"
    "\x80"
    "\x9C"
    "",
    "\xE2"
    "\x80"
    "\x9E"
    "P\xC5"
    "\x99"
    "i odes\xC3"
    "\xAD"
    "l\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " ponechat tuto obrazovku otev\xC5"
    "\x99"
    "enou\xE2"
    "\x80"
    "\x9C"
    "",
    "Displej",
    "\xC4"
    "\x8C"
    "te\xC4"
    "\x8D"
    "ka",
    "Ovl\xC3"
    "\xA1"
    "dac\xC3"
    "\xAD"
    " prvky",
    "Syst\xC3"
    "\xA9"
    "m",
    "Obrazovka sp\xC3"
    "\xA1"
    "nku",
    "Obrazovka sp\xC3"
    "\xA1"
    "nku Re\xC5"
    "\xBE"
    "im krytu",
    "Stavov\xC3"
    "\xBD"
    " \xC5"
    "\x99"
    "\xC3"
    "\xA1"
    "dek",
    "Skr\xC3"
    "\xBD"
    "t baterii %",
    "Extra mezery mezi odstavci",
    "Vyhlazov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " textu",
    "Kr\xC3"
    "\xA1"
    "tk\xC3"
    "\xA9"
    " stisknut\xC3"
    "\xAD"
    " tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tka nap\xC3"
    "\xA1"
    "jen\xC3"
    "\xAD"
    "",
    "Orientace \xC4"
    "\x8D"
    "ten\xC3"
    "\xAD"
    "",
    "Rozvr\xC5"
    "\xBE"
    "en\xC3"
    "\xAD"
    " p\xC5"
    "\x99"
    "edn\xC3"
    "\xAD"
    "ch tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tek",
    "Rozvr\xC5"
    "\xBE"
    "en\xC3"
    "\xAD"
    " bo\xC4"
    "\x8D"
    "n\xC3"
    "\xAD"
    "ch tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tek (\xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ka)",
    "Dlouh\xC3"
    "\xA9"
    " stisknut\xC3"
    "\xAD"
    " P\xC5"
    "\x99"
    "esko\xC4"
    "\x8D"
    "it kapitolu",
    "Rodina p\xC3"
    "\xAD"
    "sem \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ky",
    "P\xC3"
    "\xAD"
    "smo extern\xC3"
    "\xAD"
    " \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ky",
    "P\xC3"
    "\xAD"
    "smo \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ky",
    "P\xC3"
    "\xAD"
    "smo rozhran\xC3"
    "\xAD"
    "",
    "Velikost p\xC3"
    "\xAD"
    "sma rozhran\xC3"
    "\xAD"
    "",
    "\xC5"
    "\x98"
    "\xC3"
    "\xA1"
    "dkov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ky",
    "Mezery p\xC3"
    "\xAD"
    "smen ASCII",
    "Mezery \xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "slic ASCII",
    "Mezery CJK",
    "Re\xC5"
    "\xBE"
    "im barev",
    "Okraj obrazovky \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ky",
    "Zarovn\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " odstavc\xC5"
    "\xAF"
    " \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ky",
    "D\xC4"
    "\x9B"
    "len\xC3"
    "\xAD"
    " slov",
    "\xC4"
    "\x8C"
    "as do usp\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "",
    "Frekvence obnoven\xC3"
    "\xAD"
    "",
    "Nastaven\xC3"
    "\xAD"
    " Calibre",
    "KOReaderu Sync",
    "Zkontrolovat aktualizace",
    "Jazyk",
    "Vybrat tapetu",
    "Vymazat mezipam\xC4"
    "\x9B"
    "\xC5"
    "\xA5"
    " \xC4"
    "\x8D"
    "ten\xC3"
    "\xAD"
    "",
    "Calibre",
    "U\xC5"
    "\xBE"
    "ivatelsk\xC3"
    "\xA9"
    " jm\xC3"
    "\xA9"
    "no",
    "Heslo",
    "URL synch. serveru",
    "P\xC3"
    "\xA1"
    "rov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " dokument\xC5"
    "\xAF"
    "",
    "Ov\xC4"
    "\x9B"
    "\xC5"
    "\x99"
    "en\xC3"
    "\xAD"
    "",
    "U\xC5"
    "\xBE"
    "iv. jm\xC3"
    "\xA9"
    "no KOReaderu",
    "Heslo KOReaderu",
    "N\xC3"
    "\xA1"
    "zev souboru",
    "Bin\xC3"
    "\xA1"
    "rn\xC3"
    "\xAD"
    "",
    "Nastavte p\xC5"
    "\x99"
    "ihla\xC5"
    "\xA1"
    "ovac\xC3"
    "\xAD"
    " \xC3"
    "\xBA"
    "daje",
    "P\xC5"
    "\x99"
    "ipojen\xC3"
    "\xAD"
    " k Wi-Fi selhalo",
    "Ov\xC4"
    "\x9B"
    "\xC5"
    "\x99"
    "ov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "\xC3"
    "\x9A"
    "sp\xC4"
    "\x9B"
    "\xC5"
    "\xA1"
    "n\xC3"
    "\xA9"
    " ov\xC4"
    "\x9B"
    "\xC5"
    "\x99"
    "en\xC3"
    "\xAD"
    "!",
    "Ov\xC4"
    "\x9B"
    "\xC5"
    "\x99"
    "en\xC3"
    "\xAD"
    " KOReaderu",
    "Synchronizace KOReaderu je p\xC5"
    "\x99"
    "ipravena k pou\xC5"
    "\xBE"
    "it\xC3"
    "\xAD"
    "",
    "Ov\xC4"
    "\x9B"
    "\xC5"
    "\x99"
    "en\xC3"
    "\xAD"
    " selhalo",
    "Hotovo",
    "T\xC3"
    "\xAD"
    "mto vyma\xC5"
    "\xBE"
    "ete v\xC5"
    "\xA1"
    "echna data knih v mezipam\xC4"
    "\x9B"
    "ti.",
    "Ve\xC5"
    "\xA1"
    "ker\xC3"
    "\xBD"
    " pr\xC5"
    "\xAF"
    "b\xC4"
    "\x9B"
    "h \xC4"
    "\x8D"
    "ten\xC3"
    "\xAD"
    " bude ztracen!",
    "Knihy bude nutn\xC3"
    "\xA9"
    " znovu indexovat",
    "p\xC5"
    "\x99"
    "i op\xC4"
    "\x9B"
    "tovn\xC3"
    "\xA9"
    "m otev\xC5"
    "\x99"
    "en\xC3"
    "\xAD"
    ".",
    "Maz\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " mezipam\xC4"
    "\x9B"
    "ti...",
    "Mezipam\xC4"
    "\x9B"
    "\xC5"
    "\xA5"
    " vymaz\xC3"
    "\xA1"
    "na",
    "polo\xC5"
    "\xBE"
    "ky odstran\xC4"
    "\x9B"
    "ny",
    "selhalo",
    "Vymaz\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " mezipam\xC4"
    "\x9B"
    "ti se nezda\xC5"
    "\x99"
    "ilo",
    "Podrobnosti naleznete v s\xC3"
    "\xA9"
    "riov\xC3"
    "\xA9"
    "m v\xC3"
    "\xBD"
    "stupu",
    "Tmav\xC3"
    "\xBD"
    "",
    "Sv\xC4"
    "\x9B"
    "tl\xC3"
    "\xBD"
    "",
    "Vlastn\xC3"
    "\xAD"
    "",
    "Ob\xC3"
    "\xA1"
    "lka",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xBD"
    "",
    "P\xC5"
    "\x99"
    "izp\xC5"
    "\xAF"
    "sobit",
    "O\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "znout",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xBD"
    " postup",
    "Pln\xC3"
    "\xA1"
    "",
    "Nikdy",
    "Ve \xC4"
    "\x8D"
    "te\xC4"
    "\x8D"
    "ce",
    "V\xC5"
    "\xBE"
    "dy",
    "Ignorovat",
    "Sp\xC3"
    "\xA1"
    "nek",
    "Ot\xC3"
    "\xA1"
    "\xC4"
    "\x8D"
    "en\xC3"
    "\xAD"
    " str\xC3"
    "\xA1"
    "nek",
    "Na v\xC3"
    "\xBD"
    "\xC5"
    "\xA1"
    "ku",
    "Na \xC5"
    "\xA1"
    "\xC3"
    "\xAD"
    "\xC5"
    "\x99"
    "ku po sm\xC4"
    "\x9B"
    "ru hod. ru\xC4"
    "\x8D"
    "i\xC4"
    "\x8D"
    "ek",
    "Invertovan\xC3"
    "\xBD"
    "",
    "Na \xC5"
    "\xA1"
    "\xC3"
    "\xAD"
    "\xC5"
    "\x99"
    "ku proti sm\xC4"
    "\x9B"
    "ru hod. ru\xC4"
    "\x8D"
    "i\xC4"
    "\x8D"
    "ek",
    "Zp\xC4"
    "\x9B"
    "t, Potvrdit, Vlevo, Vpravo",
    "Vlevo, Vpravo, Zp\xC4"
    "\x9B"
    "t, Potvrdit",
    "Vlevo, Zp\xC4"
    "\x9B"
    "t, Potvrdit, Vpravo",
    "P\xC5"
    "\x99"
    "edchoz\xC3"
    "\xAD"
    "/Dal\xC5"
    "\xA1"
    "\xC3"
    "\xAD"
    "",
    "Dal\xC5"
    "\xA1"
    "\xC3"
    "\xAD"
    "/P\xC5"
    "\x99"
    "edchoz\xC3"
    "\xAD"
    "",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Mal\xC3"
    "\xBD"
    "",
    "St\xC5"
    "\x99"
    "edn\xC3"
    "\xAD"
    "",
    "Velk\xC3"
    "\xBD"
    "",
    "Ob\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "",
    "T\xC4"
    "\x9B"
    "sn\xC3"
    "\xBD"
    "",
    "Norm\xC3"
    "\xA1"
    "ln\xC3"
    "\xAD"
    "",
    "\xC5"
    "\xA0"
    "irok\xC3"
    "\xBD"
    "",
    "Zarovnat do bloku",
    "Vlevo",
    "Na st\xC5"
    "\x99"
    "ed",
    "Vpravo",
    "1 min",
    "5 min",
    "10 min",
    "15 min",
    "30 min",
    "1 str\xC3"
    "\xA1"
    "nka",
    "5 str\xC3"
    "\xA1"
    "nek",
    "10 str\xC3"
    "\xA1"
    "nek",
    "15 str\xC3"
    "\xA1"
    "nek",
    "30 str\xC3"
    "\xA1"
    "nek",
    "Aktualizace",
    "Kontrola aktualizac\xC3"
    "\xAD"
    "\xE2"
    "\x80"
    "\xA6"
    "",
    "Nov\xC3"
    "\xA1"
    " aktualizace k dispozici!",
    "Aktu\xC3"
    "\xA1"
    "ln\xC3"
    "\xAD"
    " verze:",
    "Nov\xC3"
    "\xA1"
    " verze:",
    "Aktualizace...",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA1"
    " aktualizace k dispozici",
    "Aktualizace selhala",
    "Aktualizace dokon\xC4"
    "\x8D"
    "ena",
    "Stiskn\xC4"
    "\x9B"
    "te a podr\xC5"
    "\xBE"
    "te tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko nap\xC3"
    "\xA1"
    "jen\xC3"
    "\xAD"
    " pro op\xC4"
    "\x9B"
    "tovn\xC3"
    "\xA9"
    " zapnut\xC3"
    "\xAD"
    "",
    "Extern\xC3"
    "\xAD"
    " p\xC3"
    "\xAD"
    "smo",
    "Vestav\xC4"
    "\x9B"
    "n\xC3"
    "\xA9"
    " (Zak\xC3"
    "\xA1"
    "z\xC3"
    "\xA1"
    "no)",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA9"
    " polo\xC5"
    "\xBE"
    "ky nenalezeny",
    "Stahov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "Stahov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " selhalo",
    "Chyba:",
    "Nepojmenovan\xC3"
    "\xA9"
    "",
    "Nen\xC3"
    "\xAD"
    " nakonfigurov\xC3"
    "\xA1"
    "na adresa URL serveru",
    "Na\xC4"
    "\x8D"
    "ten\xC3"
    "\xAD"
    " kan\xC3"
    "\xA1"
    "lu se nezda\xC5"
    "\x99"
    "ilo",
    "Analyzov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " kan\xC3"
    "\xA1"
    "lu se nezda\xC5"
    "\x99"
    "ilo",
    "S\xC3"
    "\xAD"
    "\xC5"
    "\xA5"
    ":",
    "IP adresa:",
    "nebo naskenujte QR k\xC3"
    "\xB3"
    "d telefonem pro p\xC5"
    "\x99"
    "ipojen\xC3"
    "\xAD"
    " k Wi-Fi.",
    "Chyba: Obecn\xC3"
    "\xA1"
    " chyba",
    "Chyba: S\xC3"
    "\xAD"
    "\xC5"
    "\xA5"
    " nenalezena",
    "Chyba: \xC4"
    "\x8C"
    "asov\xC3"
    "\xBD"
    " limit p\xC5"
    "\x99"
    "ipojen\xC3"
    "\xAD"
    "",
    "SD karta",
    "\xC2"
    "\xAB"
    " Zp\xC4"
    "\x9B"
    "t",
    "\xC2"
    "\xAB"
    " Konec",
    "\xC2"
    "\xAB"
    " Dom\xC5"
    "\xAF"
    "",
    "\xC2"
    "\xAB"
    " Ulo\xC5"
    "\xBE"
    "it",
    "Vybrat",
    "P\xC5"
    "\x99"
    "epnout",
    "Potvrdit",
    "Zru\xC5"
    "\xA1"
    "it",
    "P\xC5"
    "\x99"
    "ipojit",
    "Otev\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "t",
    "St\xC3"
    "\xA1"
    "hnout",
    "Zkusit znovu",
    "Ano",
    "Ne",
    "ZAP",
    "VYP",
    "Nastavit",
    "Nenastaveno",
    "Vlevo",
    "Vpravo",
    "Nahoru",
    "Dol\xC5"
    "\xAF"
    "",
    "P\xC3"
    "\x8D"
    "SMO",
    "p\xC3"
    "\xAD"
    "smo",
    "OK",
    "[ZAP]",
    "Filtr obrazovky sp\xC3"
    "\xA1"
    "nku",
    "Kontrast",
    "Pln\xC3"
    "\xBD"
    " s procenty",
    "Pln\xC3"
    "\xBD"
    " s pruhem knih",
    "Pouze pruh knih",
    "Pln\xC3"
    "\xA1"
    " s pruhem kapitol",
    "\xC5"
    "\xA0"
    "ablona rozhran\xC3"
    "\xAD"
    "",
    "Klasick\xC3"
    "\xA1"
    "",
    "Lyra",
    "Oprava blednut\xC3"
    "\xAD"
    " na slunci",
    "P\xC5"
    "\x99"
    "emapovat p\xC5"
    "\x99"
    "edn\xC3"
    "\xAD"
    " tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tka",
    "Prohl\xC3"
    "\xAD"
    "\xC5"
    "\xBE"
    "e\xC4"
    "\x8D"
    " OPDS",
    "Ob\xC3"
    "\xA1"
    "lka + Vlastn\xC3"
    "\xAD"
    "",
    "Ned\xC3"
    "\xA1"
    "vn\xC3"
    "\xA9"
    "",
    "Ned\xC3"
    "\xA1"
    "vn\xC3"
    "\xA9"
    " knihy",
    "\xC5"
    "\xBD"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xA9"
    " ned\xC3"
    "\xA1"
    "vn\xC3"
    "\xA9"
    " knihy",
    "Pou\xC5"
    "\xBE"
    "\xC3"
    "\xAD"
    "vat p\xC5"
    "\x99"
    "enosy bezdr\xC3"
    "\xA1"
    "tov\xC3"
    "\xBD"
    "ch za\xC5"
    "\x99"
    "\xC3"
    "\xAD"
    "zen\xC3"
    "\xAD"
    " Calibre",
    "Zapomenout s\xC3"
    "\xAD"
    "\xC5"
    "\xA5"
    " a odstranit ulo\xC5"
    "\xBE"
    "en\xC3"
    "\xA9"
    " heslo?",
    "Zapomenout na s\xC3"
    "\xAD"
    "\xC5"
    "\xA5"
    "",
    "Spu\xC5"
    "\xA1"
    "t\xC4"
    "\x9B"
    "n\xC3"
    "\xAD"
    " Calibre...",
    "Nastaven\xC3"
    "\xAD"
    "",
    "Stav",
    "Vymazat",
    "V\xC3"
    "\xBD"
    "choz\xC3"
    "\xAD"
    "",
    "Stiskn\xC4"
    "\x9B"
    "te p\xC5"
    "\x99"
    "edn\xC3"
    "\xAD"
    " tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko pro ka\xC5"
    "\xBE"
    "dou roli",
    "Nep\xC5"
    "\x99"
    "i\xC5"
    "\x99"
    "azeno",
    "Ji\xC5"
    "\xBE"
    " p\xC5"
    "\x99"
    "i\xC5"
    "\x99"
    "azeno",
    "Bo\xC4"
    "\x8D"
    "n\xC3"
    "\xAD"
    " tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko Nahoru: Obnovit v\xC3"
    "\xBD"
    "choz\xC3"
    "\xAD"
    " rozvr\xC5"
    "\xBE"
    "en\xC3"
    "\xAD"
    "",
    "Bo\xC4"
    "\x8D"
    "n\xC3"
    "\xAD"
    " tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko Dol\xC5"
    "\xAF"
    ": Zru\xC5"
    "\xA1"
    "it p\xC5"
    "\x99"
    "emapov\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "",
    "Zp\xC4"
    "\x9B"
    "t (1. tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko)",
    "Potvrdit (2. tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko)",
    "Vlevo (3. tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko)",
    "Vpravo (4. tla\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tko)",
    "P\xC5"
    "\x99"
    "ej\xC3"
    "\xAD"
    "t na %",
    "P\xC5"
    "\x99"
    "ej\xC3"
    "\xAD"
    "t Dom\xC5"
    "\xAF"
    "",
    "Pr\xC5"
    "\xAF"
    "b\xC4"
    "\x9B"
    "h synchronizace",
    "Smazat mezipam\xC4"
    "\x9B"
    "\xC5"
    "\xA5"
    " knihy",
    "Kapitola:",
    "str\xC3"
    "\xA1"
    "nek |",
    "Kniha:",
    "shift",
    "SHIFT",
    "Z\xC3"
    "\x81"
    "MEK",
    "Pro Calibre p\xC5"
    "\x99"
    "idejte /opds do URL adresy",
    "Vlevo/Vpravo: 1 % Nahoru/Dol\xC5"
    "\xAF"
    ": 10 %",
    "\xC4"
    "\x8C"
    "as synchronizace...",
    "V\xC3"
    "\xBD"
    "po\xC4"
    "\x8D"
    "et hashe dokumentu...",
    "Nepoda\xC5"
    "\x99"
    "ilo se vypo\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "tat hash dokumentu",
    "Na\xC4"
    "\x8D"
    "\xC3"
    "\xAD"
    "t\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    " vzd\xC3"
    "\xA1"
    "len\xC3"
    "\xA9"
    "ho pr\xC5"
    "\xAF"
    "b\xC4"
    "\x9B"
    "hu...",
    "Pr\xC5"
    "\xAF"
    "b\xC4"
    "\x9B"
    "h nahr\xC3"
    "\xA1"
    "v\xC3"
    "\xA1"
    "n\xC3"
    "\xAD"
    "...",
    "P\xC5"
    "\x99"
    "ihla\xC5"
    "\xA1"
    "ovac\xC3"
    "\xAD"
    " \xC3"
    "\xBA"
    "daje nejsou nakonfigurov\xC3"
    "\xA1"
    "ny",
    "Nastavit \xC3"
    "\xBA"
    "\xC4"
    "\x8D"
    "et KOReader v Nastaven\xC3"
    "\xAD"
    "",
    "Nalezen pr\xC5"
    "\xAF"
    "b\xC4"
    "\x9B"
    "h!",
    "Vzd\xC3"
    "\xA1"
    "len\xC3"
    "\xA9"
    ":",
    "Lok\xC3"
    "\xA1"
    "ln\xC3"
    "\xAD"
    ":",
    "Str\xC3"
    "\xA1"
    "nka %d, celkov\xC4"
    "\x9B"
    " %.2f%%",
    "Str\xC3"
    "\xA1"
    "nka %d/%d, celkov\xC4"
    "\x9B"
    " %.2f%%",
    "  Od: %s",
    "Pou\xC5"
    "\xBE"
    "\xC3"
    "\xAD"
    "t vzd\xC3"
    "\xA1"
    "len\xC3"
    "\xBD"
    " postup",
    "Nahr\xC3"
    "\xA1"
    "t lok\xC3"
    "\xA1"
    "ln\xC3"
    "\xAD"
    " postup",
    "Nenalezen \xC5"
    "\xBE"
    "\xC3"
    "\xA1"
    "dn\xC3"
    "\xBD"
    " vzd\xC3"
    "\xA1"
    "len\xC3"
    "\xBD"
    " postup",
    "Nahr\xC3"
    "\xA1"
    "t aktu\xC3"
    "\xA1"
    "ln\xC3"
    "\xAD"
    " pozici?",
    "Postup nahr\xC3"
    "\xA1"
    "n!",
    "Synchronizace se nezda\xC5"
    "\x99"
    "ila",
    "Sekce",
    "Nahr\xC3"
    "\xA1"
    "t",
    "Styl knihy",
    "Vlo\xC5"
    "\xBE"
    "en\xC3"
    "\xBD"
    " styl",
    "URL serveru OPDS",
};

}  // namespace i18n_strings

// Compile-time validation of array sizes
static_assert(sizeof(i18n_strings::STRINGS_EN) / sizeof(i18n_strings::STRINGS_EN[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_EN size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_SP) / sizeof(i18n_strings::STRINGS_SP[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_SP size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_IT) / sizeof(i18n_strings::STRINGS_IT[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_IT size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_SW) / sizeof(i18n_strings::STRINGS_SW[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_SW size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_FR) / sizeof(i18n_strings::STRINGS_FR[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_FR size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_DE) / sizeof(i18n_strings::STRINGS_DE[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_DE size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_CZ) / sizeof(i18n_strings::STRINGS_CZ[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_CZ size mismatch");
