#!/usr/bin/env python3
# Pocket Library for CrossPoint
# Copyright (C) 2026 Pocket Library contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate src/ZimFoldTable.inc: the search-key folding table.

Search keys are compared case- and accent-insensitively. The device folds
the typed query and the Mac folds every title with the SAME table, so the
two can never disagree. For each code point in the covered ranges the table
gives the folded replacement when it differs from the code point itself:
  1. NFKD decomposition, combining marks (category Mn) dropped;
  2. full case folding (str.casefold);
  3. a few letters with no decomposition mapped by hand (ø, ł, æ, ...);
  4. typographic punctuation mapped to ASCII (curly quotes, dashes, NBSP).
Code points outside the covered ranges pass through unchanged.

Re-run after changing the rules:  python3 lib/zim/scripts/gen_fold_table.py
"""
import os
import unicodedata

RANGES = [
    (0x0080, 0x024F),  # Latin-1 Supplement, Latin Extended-A/B
    (0x0250, 0x02AF),  # IPA extensions (a few fold)
    (0x0370, 0x03FF),  # Greek
    (0x0400, 0x052F),  # Cyrillic + supplement
    (0x1E00, 0x1EFF),  # Latin Extended Additional (Vietnamese etc.)
    (0x2000, 0x206F),  # General punctuation
    (0xFB00, 0xFB06),  # Latin ligatures ﬁ ﬂ
]
MANUAL = {
    "ß": "ss", "ẞ": "ss", "æ": "ae", "Æ": "ae", "œ": "oe", "Œ": "oe",
    "ø": "o", "Ø": "o", "đ": "d", "Đ": "d", "ð": "d", "Ð": "d", "þ": "th", "Þ": "th",
    "ł": "l", "Ł": "l", "ħ": "h", "Ħ": "h", "ı": "i", "ŀ": "l", "Ŀ": "l", "ŧ": "t", "Ŧ": "t",
    "ƒ": "f", "ŋ": "ng", "Ŋ": "ng", "ĸ": "k",
    " ": " ", " ": " ", " ": " ", " ": " ", " ": " ", " ": " ",
    "‐": "-", "‑": "-", "‒": "-", "–": "-", "—": "-", "―": "-",
    "‘": "'", "’": "'", "‚": "'", "‛": "'",
    "“": '"', "”": '"', "„": '"', "‟": '"',
    "…": "...", "·": "·",
    "​": "", "‌": "", "‍": "", "⁠": "", "­": "",
}


def fold(ch: str) -> str:
    if ch in MANUAL:
        return MANUAL[ch]
    cat = unicodedata.category(ch)
    if cat.startswith("C"):  # controls and unassigned stay as they are
        return ch
    d = "".join(c for c in unicodedata.normalize("NFKD", ch) if unicodedata.category(c) != "Mn")
    d = d.casefold()
    out = "".join(MANUAL.get(c, c) for c in d)
    return out


def main():
    rows = []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            f = fold(ch)
            if f != ch:
                rows.append((cp, f))
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "..", "src", "ZimFoldTable.inc")
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("// Generated by lib/zim/scripts/gen_fold_table.py from Python %s's Unicode %s\n"
                  % (os.sys.version.split()[0], unicodedata.unidata_version))
        out.write("// database. Do not edit by hand. {code point, folded UTF-8}; sorted by code point.\n")
        for cp, f in rows:
            lit = "".join("\\x%02x" % b for b in f.encode("utf-8"))
            out.write('{0x%04X, "%s"},\n' % (cp, lit))
    print("wrote %d rows to %s" % (len(rows), os.path.normpath(out_path)))


if __name__ == "__main__":
    main()
