// Writes lib/OtShaper/OtUnicodeData.h from HarfBuzz's own Unicode and shaper
// tables, so the shaper classifies characters exactly as HarfBuzz does.
// Built and run by gen_ot_shaper_tables.py against a pinned HarfBuzz release; never
// part of the firmware.

#include "hb.hh"
#include "hb-ot-shaper-indic.hh"
#include "hb-ot-shaper-use-table.hh"

#include <cstdio>
#include <vector>

static const hb_codepoint_t kFirst = 0x0900, kLast = 0x0DFF;
static const hb_codepoint_t kExtras[] = {0x200C, 0x200D, 0x25CC};

// Languages written in the scripts the shaper handles (BCP 47 primary subtags).
static const char* kLanguages[] = {
    "as", "awa", "bh", "bho", "bn", "bpy", "bra", "brx", "doi", "dv", "gbm", "gom", "gu", "hi", "hne", "kfr", "kn",
    "kok", "kru", "ks", "mag", "mai", "ml", "mni", "mr", "mwr", "ne", "new", "or", "pa", "pi", "raj", "sa", "sat",
    "sck", "sd", "si", "ta", "tcy", "te", "xnr", "en"};

static uint32_t pack(hb_codepoint_t u) {
  hb_unicode_funcs_t* uf = hb_unicode_funcs_get_default();
  const unsigned genCat = hb_unicode_general_category(uf, u);
  const unsigned ccc = uf->modified_combining_class(u);
  const uint16_t indic = hb_indic_get_categories(u);
  const unsigned useCat = hb_use_get_category(u);
  const unsigned ignorable = uf->is_default_ignorable(u) ? 1 : 0;
  if ((indic & 0xFF) > 63 || (indic >> 8) > 15 || useCat > 63) {
    fprintf(stderr, "U+%04X: category out of range\n", u);
    exit(1);
  }
  // genCat:5 | ccc:8 | indicCat:6 | indicPos:4 | useCat:6 | ignorable:1
  return genCat | (ccc << 5) | ((indic & 0xFFu) << 13) | ((indic >> 8) << 19) | (useCat << 23) | (ignorable << 29);
}

static bool inSet(hb_codepoint_t u) {
  if (u >= kFirst && u <= kLast) return true;
  for (hb_codepoint_t e : kExtras)
    if (u == e) return true;
  return false;
}

int main() {
  hb_unicode_funcs_t* uf = hb_unicode_funcs_get_default();
  printf("#pragma once\n\n");
  printf("// Generated by scripts/gen_ot_shaper_tables.py from HarfBuzz %s. Do not edit.\n\n", HB_VERSION_STRING);
  printf("#include <cstdint>\n\nnamespace ot::ucd {\n\n");
  printf("// Character properties, packed: general category, modified combining\n");
  printf("// class, Indic category and position, USE category, default-ignorable flag.\n");
  printf("constexpr unsigned GEN_CAT_SHIFT = 0, GEN_CAT_BITS = 5;\n");
  printf("constexpr unsigned CCC_SHIFT = 5, CCC_BITS = 8;\n");
  printf("constexpr unsigned INDIC_CAT_SHIFT = 13, INDIC_CAT_BITS = 6;\n");
  printf("constexpr unsigned INDIC_POS_SHIFT = 19, INDIC_POS_BITS = 4;\n");
  printf("constexpr unsigned USE_CAT_SHIFT = 23, USE_CAT_BITS = 6;\n");
  printf("constexpr unsigned IGNORABLE_SHIFT = 29;\n");
  printf("constexpr uint32_t FIRST = 0x%04X;\nconstexpr uint32_t LAST = 0x%04X;\n", kFirst, kLast);
  // Few distinct values: each codepoint stores an index into PROPS.
  std::vector<uint32_t> props;
  std::vector<uint8_t> index;
  for (hb_codepoint_t u = kFirst; u <= kLast; u++) {
    const uint32_t p = pack(u);
    size_t i = 0;
    while (i < props.size() && props[i] != p) i++;
    if (i == props.size()) props.push_back(p);
    if (i > 255) {
      fprintf(stderr, "more than 256 distinct property values\n");
      exit(1);
    }
    index.push_back(static_cast<uint8_t>(i));
  }
  printf("constexpr uint32_t PROPS[] = {");
  for (size_t i = 0; i < props.size(); i++) printf("%s0x%08X,", i % 8 ? " " : "\n    ", props[i]);
  printf("\n};\n");
  printf("// Per codepoint FIRST..LAST, its PROPS index.\n");
  printf("constexpr uint8_t PROPS_INDEX[] = {");
  for (size_t i = 0; i < index.size(); i++) printf("%s%u,", i % 16 ? " " : "\n    ", index[i]);
  printf("\n};\n");
  printf("constexpr uint32_t ZWNJ_PROPS = 0x%08X;\n", pack(0x200C));
  printf("constexpr uint32_t ZWJ_PROPS = 0x%08X;\n", pack(0x200D));
  printf("constexpr uint32_t DOTTED_CIRCLE_PROPS = 0x%08X;\n\n", pack(0x25CC));

  // Canonical decompositions within the set (one step, as hb_unicode_decompose).
  printf("struct Decomposition {\n  uint16_t ab, a, b;\n};\nconstexpr Decomposition DECOMPOSITIONS[] = {\n");
  std::vector<hb_codepoint_t> all;
  for (hb_codepoint_t u = kFirst; u <= kLast; u++) all.push_back(u);
  for (hb_codepoint_t e : kExtras) all.push_back(e);
  for (hb_codepoint_t u : all) {
    hb_codepoint_t a = 0, b = 0;
    if (!hb_unicode_decompose(uf, u, &a, &b)) continue;
    if (!inSet(a) || (b && !inSet(b))) {
      fprintf(stderr, "U+%04X decomposes outside the set\n", u);
      exit(1);
    }
    printf("    {0x%04X, 0x%04X, 0x%04X},\n", u, a, b);
  }
  printf("};\n\n");

  // Canonical compositions of two codepoints of the set.
  printf("struct Composition {\n  uint16_t a, b, ab;\n};\nconstexpr Composition COMPOSITIONS[] = {\n");
  for (hb_codepoint_t a : all)
    for (hb_codepoint_t b : all) {
      hb_codepoint_t ab = 0;
      if (hb_unicode_compose(uf, a, b, &ab)) {
        if (!inSet(ab)) {
          fprintf(stderr, "U+%04X+U+%04X composes outside the set\n", a, b);
          exit(1);
        }
        printf("    {0x%04X, 0x%04X, 0x%04X},\n", a, b, ab);
      }
    }
  printf("};\n\n");

  // OpenType language system tags HarfBuzz tries for each language, in order.
  printf("struct LanguageTags {\n  char code[4];\n  uint32_t tags[3];\n};\nconstexpr LanguageTags LANGUAGES[] = {\n");
  for (const char* code : kLanguages) {
    unsigned scriptCount = 0, languageCount = 3;
    hb_tag_t tags[3] = {};
    hb_ot_tags_from_script_and_language(HB_SCRIPT_DEVANAGARI, hb_language_from_string(code, -1), &scriptCount, nullptr,
                                        &languageCount, tags);
    printf("    {\"%s\", {", code);
    for (unsigned i = 0; i < 3; i++) printf("%s0x%08X", i ? ", " : "", i < languageCount ? tags[i] : 0);
    printf("}},  //");
    for (unsigned i = 0; i < languageCount; i++) printf(" '%c%c%c%c'", HB_UNTAG(tags[i]));
    printf("\n");
  }
  printf("};\n\n}  // namespace ot::ucd\n");
  return 0;
}
