#!/usr/bin/env python3
"""Generate lib/ThaiDict/ThaiDictData.h from the ICU Thai wordlist.

The ICU wordlist (thaidict.txt) drives Thai word segmentation for line
breaking and dictionary word selection. Words are stored as a front-coded
sorted list in blocks of 16, with a uint32 offset table per block — the most
compact of the encodings evaluated (132 KB vs 168 KB DAWG / 352 KB trie for
the 26k-word list) while still supporting binary-search longest-prefix match.

Encoding (all chars byte-mapped as codepoint - 0x0E00, valid range 1..0x5B):
  block table: uint32 byte offset into the data array, one per block
  block entry 0:      [wordLen u8][mapped bytes...]
  block entries 1-15: [sharedPrefixLen u8][suffixLen u8][suffix bytes...]

Usage:
  python scripts/gen_thai_dict.py thaidict.txt lib/ThaiDict/ThaiDictData.h

Source wordlist (not committed; ~400 KB):
  https://raw.githubusercontent.com/unicode-org/icu/main/icu4c/source/data/brkitr/dictionaries/thaidict.txt
"""

import sys

BLOCK = 16


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]

    words = set()
    with open(src, encoding="utf-8-sig") as f:
        for line in f:
            w = line.strip()
            if not w or w.startswith("#"):
                continue
            # Pure-Thai entries only; a handful carry punctuation or Latin.
            if all(0x0E01 <= ord(c) <= 0x0E5B for c in w):
                words.add(w)

    encoded = sorted(bytes(ord(c) - 0x0E00 for c in w) for w in words)
    max_len = max(len(e) for e in encoded)
    assert max_len <= 255

    data = bytearray()
    offsets = []
    for i, e in enumerate(encoded):
        if i % BLOCK == 0:
            offsets.append(len(data))
            data.append(len(e))
            data.extend(e)
        else:
            prev = encoded[i - 1]
            p = 0
            while p < len(prev) and p < len(e) and prev[p] == e[p]:
                p += 1
            data.append(p)
            data.append(len(e) - p)
            data.extend(e[p:])

    def dump(vals, fmt, per_line):
        lines = []
        for i in range(0, len(vals), per_line):
            lines.append("    " + ", ".join(fmt(v) for v in vals[i : i + per_line]) + ",")
        return "\n".join(lines)

    with open(dst, "w", encoding="utf-8") as f:
        f.write(f"""\
// Generated by scripts/gen_thai_dict.py — DO NOT EDIT.
//
// Thai word list from ICU (thaidict.txt), used for word-boundary
// segmentation. Word data:
//   Copyright (C) 2016 and later: Unicode, Inc. and others.
//   License & terms of use: http://www.unicode.org/copyright.html
//   Copyright (c) 2006-2015 International Business Machines Corporation,
//   Apple Inc., and others. All Rights Reserved.
//
// {len(encoded)} words, front-coded in blocks of {BLOCK} ({len(data)} data bytes).
#pragma once
#include <cstdint>

namespace thaidict {{

constexpr uint32_t WORD_COUNT = {len(encoded)};
constexpr uint32_t BLOCK_SIZE = {BLOCK};
constexpr uint32_t BLOCK_COUNT = {len(offsets)};
constexpr uint32_t MAX_WORD_LEN = {max_len};

// Byte offset of each block's first (fully spelled) word in DATA.
constexpr uint32_t BLOCK_OFFSETS[BLOCK_COUNT] = {{
{dump(offsets, lambda v: str(v), 12)}
}};

// Front-coded word data; chars are stored as (codepoint - 0x0E00).
constexpr uint8_t DATA[{len(data)}] = {{
{dump(list(data), lambda v: str(v), 20)}
}};

}}  // namespace thaidict
""")

    print(f"{len(encoded)} words -> {len(data) + len(offsets) * 4} bytes "
          f"({(len(data) + len(offsets) * 4) / 1024:.0f} KB) in {dst}")


if __name__ == "__main__":
    main()
