#!/usr/bin/env python3
# Pocket Library for CrossPoint
# Copyright (C) 2026 Pocket Library contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Draws the sleep screen's "DON'T PANIC" into a 1-bit C header.

The lettering is Fredoka (SIL Open Font License 1.1, from google/fonts) at
its heaviest weight: rounded, large and friendly. Only the rendered picture
goes into the firmware, not the font.

    pip install pillow fonttools
    python3 tools/sleep/make_dont_panic.py  # writes src/pocketlib/images/DontPanic.h
"""
import io
import pathlib
import urllib.request

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from PIL import Image, ImageDraw, ImageFont

FONT_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/fredoka/Fredoka%5Bwdth,wght%5D.ttf"
LINES = ["DON’T", "PANIC"]
WIDTH = 368  # the widest line, in pixels: the screen is 480 wide
OUT = pathlib.Path(__file__).resolve().parents[2] / "src/pocketlib/images/DontPanic.h"


def heavy_font() -> bytes:
    raw = urllib.request.urlopen(FONT_URL).read()
    font = instancer.instantiateVariableFont(TTFont(io.BytesIO(raw)), {"wght": 700, "wdth": 100})
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def render(font_bytes: bytes) -> Image.Image:
    probe = ImageDraw.Draw(Image.new("L", (1, 1)))
    size = 40
    while max(probe.textlength(l, font=ImageFont.truetype(io.BytesIO(font_bytes), size + 1)) for l in LINES) <= WIDTH:
        size += 1
    font = ImageFont.truetype(io.BytesIO(font_bytes), size)
    boxes = [probe.textbbox((0, 0), l, font=font) for l in LINES]
    cap = boxes[1][3] - boxes[1][1]  # "PANIC": no apostrophe, no descender
    gap = round(cap * 0.22)
    img = Image.new("L", (WIDTH, cap * 2 + gap), 255)
    draw = ImageDraw.Draw(img)
    for i, (line, box) in enumerate(zip(LINES, boxes)):
        x = (WIDTH - (box[2] - box[0])) // 2 - box[0]
        y = i * (cap + gap) - boxes[1][1]
        draw.text((x, y), line, font=font, fill=0)
    return img.point(lambda v: 0 if v < 128 else 255).convert("1")


def header(img: Image.Image) -> str:
    w, h = img.size
    row_bytes = (w + 7) // 8
    data = []
    px = img.load()
    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                white = x >= w or px[x, y] != 0
                byte |= (1 if white else 0) << (7 - bit)
            data.append(byte)
    rows = [", ".join(f"0x{b:02X}" for b in data[i : i + 16]) for i in range(0, len(data), 16)]
    body = ",\n    ".join(rows)
    return f"""// Pocket Library for CrossPoint
// Copyright (C) 2026 Pocket Library contributors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generated by tools/sleep/make_dont_panic.py: do not edit. "DON'T PANIC" in
// Fredoka (SIL OFL 1.1). Row by row, MSB first, 0 = ink.

#pragma once

#include <cstdint>

namespace pocketlib {{

constexpr int kDontPanicWidth = {w};
constexpr int kDontPanicHeight = {h};
inline constexpr uint8_t kDontPanicBits[] = {{
    {body}}};

}}  // namespace pocketlib
"""


if __name__ == "__main__":
    image = render(heavy_font())
    OUT.write_text(header(image))
    print(f"{OUT}: {image.size[0]}x{image.size[1]}")
