// AUTO-GENERATED FILE - do not edit manually.
// Source of truth: htmlEntities.yaml
// Regenerate by running:  python3 scripts/generate_entities.py

#include "htmlEntities.h"

#include <cstring>

static const int PRIMARY_SALT = 37;
static const int SECONDARY_SALT = 31;
static const int TABLE_SIZE = 240;

// Per-bucket displacement table
static const int DISPLACEMENTS[240] = {
    0,   0,  0, 0,   0,  0,  0,  2,  1,   7,  0,  2,  4,   0,  0,   0,   1,   2,  0,  3,  0,  5,   0,  1,   1, 0,  2,
    0,   0,  0, 2,   1,  2,  0,  0,  0,   0,  0,  1,  0,   0,  1,   2,   0,   0,  0,  1,  0,  0,   2,  0,   4, 14, 11,
    1,   0,  2, 1,   0,  1,  0,  0,  0,   0,  1,  0,  0,   1,  0,   0,   0,   2,  14, 0,  0,  0,   0,  0,   6, 3,  0,
    16,  0,  6, 16,  0,  3,  0,  0,  0,   0,  5,  1,  2,   1,  3,   5,   1,   19, 0,  0,  0,  24,  0,  1,   0, 32, 0,
    0,   23, 0, 0,   21, 0,  23, 0,  42,  1,  8,  0,  44,  1,  0,   0,   0,   16, 0,  0,  20, 0,   1,  0,   3, 0,  0,
    4,   0,  0, 0,   4,  2,  9,  1,  3,   0,  1,  0,  4,   17, 4,   1,   0,   0,  5,  20, 1,  1,   0,  28,  1, 5,  35,
    10,  0,  2, 0,   3,  2,  0,  22, 3,   94, 19, 11, 0,   0,  0,   5,   27,  2,  0,  2,  24, 103, 31, 0,   0, 48, 6,
    0,   7,  0, 16,  0,  0,  0,  0,  17,  0,  80, 63, 0,   0,  5,   127, 0,   15, 0,  4,  0,  0,   0,  151, 0, 14, 174,
    150, 8,  0, 110, 0,  93, 9,  0,  175, 0,  0,  13, 170, 0,  169, 2,   204, 0,  0,  2,  69, 0,   1,  1};

// Final hash table: each slot holds a key/value pair, or {nullptr, nullptr, 0}
struct EntitySlot {
  const char* key;    // e.g. "&amp;"  - nullptr means this slot is empty
  const char* value;  // e.g. "&"      - UTF-8, non-ASCII as \xNN escapes
  int keyLen;         // byte length of key - avoids strlen() on every lookup
};

static const EntitySlot HASH_TABLE[240] = {{"&dagger;", "\xE2\x80\xA0", 8},
                                           {"&sdot;", "\xE2\x8B\x85", 6},
                                           {"&Ouml;", "\xC3\x96", 6},
                                           {"&Aacute;", "\xC3\x81", 8},
                                           {"&copy;", "\xC2\xA9", 6},
                                           {"&Kappa;", "\xCE\x9A", 7},
                                           {"&Uuml;", "\xC3\x9C", 6},
                                           {"&rsquo;", "\xE2\x80\x99", 7},
                                           {"&frasl;", "\xE2\x81\x84", 7},
                                           {"&rdquo;", "\xE2\x80\x9D", 7},
                                           {"&Acirc;", "\xC3\x82", 7},
                                           {"&clubs;", "\xE2\x99\xA3", 7},
                                           {"&Pi;", "\xCE\xA0", 4},
                                           {"&aelig;", "\xC3\xA6", 7},
                                           {"&Lambda;", "\xCE\x9B", 8},
                                           {"&Iacute;", "\xC3\x8D", 8},
                                           {"&cent;", "\xC2\xA2", 6},
                                           {"&Omega;", "\xCE\xA9", 7},
                                           {"&auml;", "\xC3\xA4", 6},
                                           {"&sect;", "\xC2\xA7", 6},
                                           {"&Xi;", "\xCE\x9E", 4},
                                           {"&bull;", "\xE2\x80\xA2", 6},
                                           {"&Uacute;", "\xC3\x9A", 8},
                                           {"&euml;", "\xC3\xAB", 6},
                                           {"&Yuml;", "\xC5\xB8", 6},
                                           {"&hearts;", "\xE2\x99\xA5", 8},
                                           {"&iuml;", "\xC3\xAF", 6},
                                           {"&isin;", "\xE2\x88\x88", 6},
                                           {"&deg;", "\xC2\xB0", 5},
                                           {"&kappa;", "\xCE\xBA", 7},
                                           {"&Oacute;", "\xC3\x93", 8},
                                           {"&cap;", "\xE2\x88\xA9", 5},
                                           {"&ouml;", "\xC3\xB6", 6},
                                           {"&not;", "\xC2\xAC", 5},
                                           {"&aacute;", "\xC3\xA1", 8},
                                           {"&cup;", "\xE2\x88\xAA", 5},
                                           {"&Chi;", "\xCE\xA7", 5},
                                           {"&para;", "\xC2\xB6", 6},
                                           {"&uuml;", "\xC3\xBC", 6},
                                           {"&eacute;", "\xC3\xA9", 8},
                                           {"&frac12;", "\xC2\xBD", 8},
                                           {"&ccedil;", "\xC3\xA7", 8},
                                           {"&iacute;", "\xC3\xAD", 8},
                                           {"&laquo;", "\xC2\xAB", 7},
                                           {"&acirc;", "\xC3\xA2", 7},
                                           {"&chi;", "\xCF\x87", 5},
                                           {"&times;", "\xC3\x97", 7},
                                           {"&pi;", "\xCF\x80", 4},
                                           {"&omega;", "\xCF\x89", 7},
                                           {"&ldquo;", "\xE2\x80\x9C", 7},
                                           {"&lceil;", "\xE2\x8C\x88", 7},
                                           {"&sup;", "\xE2\x8A\x83", 5},
                                           {"&nbsp;", "\xC2\xA0", 6},
                                           {"&xi;", "\xCE\xBE", 4},
                                           {"&scaron;", "\xC5\xA1", 8},
                                           {"&uacute;", "\xC3\xBA", 8},
                                           {"&THORN;", "\xC3\x9E", 7},
                                           {"&tilde;", "\xCB\x9C", 7},
                                           {"&yuml;", "\xC3\xBF", 6},
                                           {"&zwnj;", "\xE2\x80\x8C", 6},
                                           {"&Oslash;", "\xC3\x98", 8},
                                           {"&infin;", "\xE2\x88\x9E", 7},
                                           {"&oline;", "\xE2\x80\xBE", 7},
                                           {"&lsquo;", "\xE2\x80\x98", 7},
                                           {"&Atilde;", "\xC3\x83", 8},
                                           {"&supe;", "\xE2\x8A\x87", 6},
                                           {"&Prime;", "\xE2\x80\xB3", 7},
                                           {"&macr;", "\xC2\xAF", 6},
                                           {"&prop;", "\xE2\x88\x9D", 6},
                                           {"&Egrave;", "\xC3\x88", 8},
                                           {"&lsaquo;", "\xE2\x80\xB9", 8},
                                           {"&Agrave;", "\xC3\x80", 8},
                                           {"&oacute;", "\xC3\xB3", 8},
                                           {"&darr;", "\xE2\x86\x93", 6},
                                           {"&rsaquo;", "\xE2\x80\xBA", 8},
                                           {"&Igrave;", "\xC3\x8C", 8},
                                           {"&Otilde;", "\xC3\x95", 8},
                                           {"&Ntilde;", "\xC3\x91", 8},
                                           {"&lambda;", "\xCE\xBB", 8},
                                           {"&yacute;", "\xC3\xBD", 8},
                                           {"&thetasym;", "\xCF\x91", 10},
                                           {"&Ograve;", "\xC3\x92", 8},
                                           {"&or;", "\xE2\x88\xA8", 4},
                                           {"&iexcl;", "\xC2\xA1", 7},
                                           {"&zwj;", "\xE2\x80\x8D", 5},
                                           {"&Ugrave;", "\xC3\x99", 8},
                                           {"&iquest;", "\xC2\xBF", 8},
                                           {"&there4;", "\xE2\x88\xB4", 8},
                                           {"&rarr;", "\xE2\x86\x92", 6},
                                           {"&eth;", "\xC3\xB0", 5},
                                           {"&mdash;", "\xE2\x80\x94", 7},
                                           {"&uarr;", "\xE2\x86\x91", 6},
                                           {"&sube;", "\xE2\x8A\x86", 6},
                                           {"&shy;", "\xC2\xAD", 5},
                                           {"&and;", "\xE2\x88\xA7", 5},
                                           {"&otimes;", "\xE2\x8A\x97", 8},
                                           {"&harr;", "\xE2\x86\x94", 6},
                                           {"&agrave;", "\xC3\xA0", 8},
                                           {"&sub;", "\xE2\x8A\x82", 5},
                                           {"&int;", "\xE2\x88\xAB", 5},
                                           {"&crarr;", "\xE2\x86\xB5", 7},
                                           {"&frac14;", "\xC2\xBC", 8},
                                           {"&fnof;", "\xC6\x92", 6},
                                           {"&egrave;", "\xC3\xA8", 8},
                                           {"&Omicron;", "\xCE\x9F", 9},
                                           {"&igrave;", "\xC3\xAC", 8},
                                           {"&lowast;", "\xE2\x88\x97", 8},
                                           {"&frac34;", "\xC2\xBE", 8},
                                           {"&larr;", "\xE2\x86\x90", 6},
                                           {"&otilde;", "\xC3\xB5", 8},
                                           {"&szlig;", "\xC3\x9F", 7},
                                           {"&eta;", "\xCE\xB7", 5},
                                           {"&forall;", "\xE2\x88\x80", 8},
                                           {"&minus;", "\xE2\x88\x92", 7},
                                           {"&ndash;", "\xE2\x80\x93", 7},
                                           {"&Scaron;", "\xC5\xA0", 8},
                                           {"&ograve;", "\xC3\xB2", 8},
                                           {"&empty;", "\xE2\x88\x85", 7},
                                           {"&Beta;", "\xCE\x92", 6},
                                           {"&ugrave;", "\xC3\xB9", 8},
                                           {"&euro;", "\xE2\x82\xAC", 6},
                                           {"&circ;", "\xCB\x86", 6},
                                           {"&prime;", "\xE2\x80\xB2", 7},
                                           {"&oplus;", "\xE2\x8A\x95", 7},
                                           {"&sbquo;", "\xE2\x80\x9A", 7},
                                           {"&atilde;", "\xC3\xA3", 8},
                                           {"&micro;", "\xC2\xB5", 7},
                                           {"&Eta;", "\xCE\x97", 5},
                                           {"&curren;", "\xC2\xA4", 8},
                                           {"&icirc;", "\xC3\xAE", 7},
                                           {"&sup1;", "\xC2\xB9", 6},
                                           {"&sigmaf;", "\xCF\x82", 8},
                                           {"&piv;", "\xCF\x96", 5},
                                           {"&Eacute;", "\xC3\x89", 8},
                                           {"&Ecirc;", "\xC3\x8A", 7},
                                           {"&ordf;", "\xC2\xAA", 6},
                                           {"&brvbar;", "\xC2\xA6", 8},
                                           {"&omicron;", "\xCE\xBF", 9},
                                           {"&plusmn;", "\xC2\xB1", 8},
                                           {"&loz;", "\xE2\x97\x8A", 5},
                                           {"&Delta;", "\xCE\x94", 7},
                                           {"&OElig;", "\xC5\x92", 7},
                                           {"&lt;", "<", 4},
                                           {"&Nu;", "\xCE\x9D", 4},
                                           {"&Aring;", "\xC3\x85", 7},
                                           {"&Mu;", "\xCE\x9C", 4},
                                           {"&diams;", "\xE2\x99\xA6", 7},
                                           {"&nsub;", "\xE2\x8A\x84", 6},
                                           {"&perp;", "\xE2\x8A\xA5", 6},
                                           {"&permil;", "\xE2\x80\xB0", 8},
                                           {"&Zeta;", "\xCE\x96", 6},
                                           {"&Ucirc;", "\xC3\x9B", 7},
                                           {"&ge;", "\xE2\x89\xA5", 4},
                                           {"&beta;", "\xCE\xB2", 6},
                                           {"&emsp;", "\xE2\x80\x83", 6},
                                           {"&gt;", ">", 4},
                                           {"&divide;", "\xC3\xB7", 8},
                                           {"&nabla;", "\xE2\x88\x87", 7},
                                           {"&ne;", "\xE2\x89\xA0", 4},
                                           {"&rlm;", "\xE2\x80\x8F", 5},
                                           {"&thinsp;", "\xE2\x80\x89", 8},
                                           {"&sup2;", "\xC2\xB2", 6},
                                           {"&radic;", "\xE2\x88\x9A", 7},
                                           {"&Alpha;", "\xCE\x91", 7},
                                           {"&cong;", "\xE2\x89\x85", 6},
                                           {"&le;", "\xE2\x89\xA4", 4},
                                           {"&yen;", "\xC2\xA5", 5},
                                           {"&Epsilon;", "\xCE\x95", 9},
                                           {"&ang;", "\xE2\x88\xA0", 5},
                                           {"&ecirc;", "\xC3\xAA", 7},
                                           {"&notin;", "\xE2\x88\x89", 7},
                                           {"&equiv;", "\xE2\x89\xA1", 7},
                                           {"&delta;", "\xCE\xB4", 7},
                                           {"&upsih;", "\xCF\x92", 7},
                                           {"&mu;", "\xCE\xBC", 4},
                                           {"&ensp;", "\xE2\x80\x82", 6},
                                           {"&aring;", "\xC3\xA5", 7},
                                           {"&Phi;", "\xCE\xA6", 5},
                                           {"&spades;", "\xE2\x99\xA0", 8},
                                           {"&Theta;", "\xCE\x98", 7},
                                           {"&prod;", "\xE2\x88\x8F", 6},
                                           {"&ucirc;", "\xC3\xBB", 7},
                                           {"&lfloor;", "\xE2\x8C\x8A", 8},
                                           {"&Upsilon;", "\xCE\xA5", 9},
                                           {"&zeta;", "\xCE\xB6", 6},
                                           {"&Rho;", "\xCE\xA1", 5},
                                           {"&sim;", "\xE2\x88\xBC", 5},
                                           {"&Tau;", "\xCE\xA4", 5},
                                           {"&rfloor;", "\xE2\x8C\x8B", 8},
                                           {"&AElig;", "\xC3\x86", 7},
                                           {"&nu;", "\xCE\xBD", 4},
                                           {"&Icirc;", "\xC3\x8E", 7},
                                           {"&gamma;", "\xCE\xB3", 7},
                                           {"&sup3;", "\xC2\xB3", 6},
                                           {"&Iota;", "\xCE\x99", 6},
                                           {"&Psi;", "\xCE\xA8", 5},
                                           {"&alpha;", "\xCE\xB1", 7},
                                           {"&oslash;", "\xC3\xB8", 8},
                                           {"&sum;", "\xE2\x88\x91", 5},
                                           {"&epsilon;", "\xCE\xB5", 9},
                                           {"&ntilde;", "\xC3\xB1", 8},
                                           {"&Yacute;", "\xC3\x9D", 8},
                                           {"&thorn;", "\xC3\xBE", 7},
                                           {"&ordm;", "\xC2\xBA", 6},
                                           {"&Sigma;", "\xCE\xA3", 7},
                                           {"&amp;", "&", 5},
                                           {"&trade;", "\xE2\x84\xA2", 7},
                                           {"&oelig;", "\xC5\x93", 7},
                                           {"&Dagger;", "\xE2\x80\xA1", 8},
                                           {"&reg;", "\xC2\xAE", 5},
                                           {"&pound;", "\xC2\xA3", 7},
                                           {"&theta;", "\xCE\xB8", 7},
                                           {"&ni;", "\xE2\x88\x8B", 4},
                                           {"&quot;", "\"", 6},
                                           {"&Gamma;", "\xCE\x93", 7},
                                           {"&part;", "\xE2\x88\x82", 6},
                                           {"&bdquo;", "\xE2\x80\x9E", 7},
                                           {"&upsilon;", "\xCF\x85", 9},
                                           {"&lrm;", "\xE2\x80\x8E", 5},
                                           {"&tau;", "\xCF\x84", 5},
                                           {"&Ocirc;", "\xC3\x94", 7},
                                           {"&uml;", "\xC2\xA8", 5},
                                           {"&phi;", "\xCF\x86", 5},
                                           {"&cedil;", "\xC2\xB8", 7},
                                           {"&psi;", "\xCF\x88", 5},
                                           {"&rho;", "\xCF\x81", 5},
                                           {"&Auml;", "\xC3\x84", 6},
                                           {"&iota;", "\xCE\xB9", 6},
                                           {"&Ccedil;", "\xC3\x87", 8},
                                           {"&hellip;", "\xE2\x80\xA6", 8},
                                           {"&raquo;", "\xC2\xBB", 7},
                                           {"&asymp;", "\xE2\x89\x88", 7},
                                           {"&Euml;", "\xC3\x8B", 6},
                                           {"&ETH;", "\xC3\x90", 5},
                                           {"&Iuml;", "\xC3\x8F", 6},
                                           {"&exist;", "\xE2\x88\x83", 7},
                                           {"&sigma;", "\xCF\x83", 7},
                                           {"&ocirc;", "\xC3\xB4", 7},
                                           {"&rceil;", "\xE2\x8C\x89", 7},
                                           {"&acute;", "\xC2\xB4", 7}};

// Polynomial hash
static int polyHash(const char* key, int len, int salt) {
  int h = 0;
  for (int i = 0; i < len; ++i) {
    h = (h * salt + (unsigned char)key[i]) % TABLE_SIZE;
  }
  return h;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------
const char* lookupHtmlEntity(const char* entity, int len) {
  // Prevent hashing overhead for impossible lengths
  if (len < 4 || len > 33) {
    return nullptr;
  }

  int bucket = polyHash(entity, len, PRIMARY_SALT);
  int slot = (polyHash(entity, len, SECONDARY_SALT) + DISPLACEMENTS[bucket]) % TABLE_SIZE;
  const EntitySlot& s = HASH_TABLE[slot];
  if (s.key != nullptr && s.keyLen == len && memcmp(s.key, entity, len) == 0) {
    return s.value;
  }
  return nullptr;
}
