#pragma once

#include <I18nKeys.h>

#include <cstdint>

struct ClockTimeZoneInfo {
  StrId label;
  const char* posixRule;
  int16_t standardOffsetMinutes;
};

enum ClockTimeZone : uint8_t {
  CLOCK_TZ_UTC = 0,
  CLOCK_TZ_PACIFIC_HONOLULU,
  CLOCK_TZ_AMERICA_ANCHORAGE,
  CLOCK_TZ_AMERICA_LOS_ANGELES,
  CLOCK_TZ_AMERICA_PHOENIX,
  CLOCK_TZ_AMERICA_DENVER,
  CLOCK_TZ_AMERICA_CHICAGO,
  CLOCK_TZ_AMERICA_NEW_YORK,
  CLOCK_TZ_AMERICA_HALIFAX,
  CLOCK_TZ_AMERICA_ST_JOHNS,
  CLOCK_TZ_AMERICA_SAO_PAULO,
  CLOCK_TZ_ATLANTIC_SOUTH_GEORGIA,
  CLOCK_TZ_ATLANTIC_AZORES,
  CLOCK_TZ_EUROPE_LONDON,
  CLOCK_TZ_EUROPE_PARIS,
  CLOCK_TZ_EUROPE_HELSINKI,
  CLOCK_TZ_AFRICA_JOHANNESBURG,
  CLOCK_TZ_EUROPE_MOSCOW,
  CLOCK_TZ_ASIA_RIYADH,
  CLOCK_TZ_ASIA_TEHRAN,
  CLOCK_TZ_ASIA_DUBAI,
  CLOCK_TZ_ASIA_KABUL,
  CLOCK_TZ_ASIA_KARACHI,
  CLOCK_TZ_ASIA_KOLKATA,
  CLOCK_TZ_ASIA_KATHMANDU,
  CLOCK_TZ_ASIA_DHAKA,
  CLOCK_TZ_ASIA_YANGON,
  CLOCK_TZ_ASIA_BANGKOK,
  CLOCK_TZ_ASIA_SHANGHAI,
  CLOCK_TZ_AUSTRALIA_PERTH,
  CLOCK_TZ_ASIA_TOKYO,
  CLOCK_TZ_AUSTRALIA_ADELAIDE,
  CLOCK_TZ_AUSTRALIA_DARWIN,
  CLOCK_TZ_AUSTRALIA_BRISBANE,
  CLOCK_TZ_AUSTRALIA_SYDNEY,
  CLOCK_TZ_PACIFIC_NOUMEA,
  CLOCK_TZ_PACIFIC_AUCKLAND,
  CLOCK_TZ_PACIFIC_CHATHAM,
  CLOCK_TZ_PACIFIC_TONGATAPU,
  CLOCK_TZ_PACIFIC_KIRITIMATI,
  CLOCK_TIME_ZONE_COUNT,
};

const ClockTimeZoneInfo& getClockTimeZone(uint8_t index);
uint8_t clockTimeZoneFromLegacyOffset(uint8_t biasedQuarterHours);
