// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_12_FONT_ID (-645779919)
#define BOOKERLY_14_FONT_ID (-1017028508)
#define BOOKERLY_16_FONT_ID (212304301)
#define NOTOSANS_12_FONT_ID (1127091783)
#define NOTOSANS_14_FONT_ID (-1971355903)
#define NOTOSANS_16_FONT_ID (-1168468427)
#define NOTOSANSCJK_14_FONT_ID (630682446)
#define UI_10_FONT_ID (-1923521310)
#define UI_12_FONT_ID (1793806089)
#define SMALL_FONT_ID (-66720730)
