// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (1453662115)
#define NOTOSERIF_14_FONT_ID (397399770)
#define NOTOSERIF_16_FONT_ID (1083169235)
#define NOTOSERIF_18_FONT_ID (-889312624)
#define NOTOSANS_12_FONT_ID (-960553730)
#define NOTOSANS_14_FONT_ID (96755156)
#define NOTOSANS_16_FONT_ID (-454779349)
#define NOTOSANS_18_FONT_ID (25500294)
#define UI_10_FONT_ID (-32940097)
#define UI_12_FONT_ID (1166208414)
#define SMALL_FONT_ID (-1652269921)
#define IPA_FONT_ID (1690626997)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IPA_FONT_ID != 0, "Font ID collision with sentinel");
